.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/af_shader.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/af_shader.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <glm\&.hpp>\fP
.br
\fC#include <gtc/matrix_transform\&.hpp>\fP
.br
\fC#include <gtc/type_ptr\&.hpp>\fP
.br
\fC#include <glm/gtx/norm\&.hpp>\fP
.br
\fC#include <GL/gl3w\&.h>\fP
.br
\fC#include 'fab\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBshader_variable\fP"
.br
.RI "\fIbasic variable type of the shader 
.br
\fP"
.ti -1c
.RI "class \fBaf_shader\fP"
.br
.RI "\fI\fBaf_shader\fP, process unit of gpu for rendering ui components 
.br
\fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef map< string, \fBshader_variable\fP > \fBmshader_variable_list\fP"
.br
.ti -1c
.RI "typedef map< string, shared_ptr< \fBaf_shader\fP > > \fBmaf_shader\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmaf_shader\fP \fBg_af_shader_list\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef map<string,shared_ptr<\fBaf_shader\fP> > \fBmaf_shader\fP"

.SS "typedef map<string, \fBshader_variable\fP> \fBmshader_variable_list\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBmaf_shader\fP g_af_shader_list"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
