.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/afb_load.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/afb_load.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'afb_load\&.h'\fP
.br
\fC#include <msgpack\&.hpp>\fP
.br
\fC#include 'factory\&.h'\fP
.br
\fC#include 'res_output\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'imgui\&.h'\fP
.br
\fC#include <GL/gl3w\&.h>\fP
.br
\fC#include 'af_shader\&.h'\fP
.br
\fC#include 'material\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBREGISTER_CONTROL\fP(T, \&.\&.\&.)   \fBREGISTER_CONTROL_BYKEY\fP(T,#T,##__VA_ARGS__)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_ui_component_by_mgo\fP (\fBbase_ui_component\fP *&ptar, msgpack::v2::object &obj)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define REGISTER_CONTROL(T,  \&.\&.\&.)   \fBREGISTER_CONTROL_BYKEY\fP(T,#T,##__VA_ARGS__)"

.SH "Function Documentation"
.PP 
.SS "void init_ui_component_by_mgo (\fBbase_ui_component\fP *& ptar, msgpack::v2::object & obj)"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
