.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/afb_output.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/afb_output.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'afb_output\&.h'\fP
.br
\fC#include <msgpack\&.hpp>\fP
.br
\fC#include 'res_output\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'imgui\&.h'\fP
.br
\fC#include <GL/gl3w\&.h>\fP
.br
\fC#include 'af_shader\&.h'\fP
.br
\fC#include 'material\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpack_ui_component_data\fP (\fBbase_ui_component\fP &tar, msgpack::packer< ofstream > &pk)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void pack_ui_component_data (\fBbase_ui_component\fP & tar, msgpack::packer< ofstream > & pk)"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
