.TH "afb_load" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
afb_load \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <afb_load\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBafb_load\fP (\fBbase_ui_component\fP *&pr_root)"
.br
.ti -1c
.RI "\fB~afb_load\fP ()"
.br
.ti -1c
.RI "void \fBload_afb\fP (const char *afb_file)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBbase_ui_component\fP *& \fB_pj\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "afb_load::afb_load (\fBbase_ui_component\fP *& pr_root)\fC [inline]\fP"

.SS "afb_load::~afb_load ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void afb_load::load_afb (const char * afb_file)"

.SH "Member Data Documentation"
.PP 
.SS "\fBbase_ui_component\fP*& afb_load::_pj\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
