.TH "base_ui_component::internal_property" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
base_ui_component::internal_property \- define the property data block
.br
 

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <control_common_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinternal_property\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fB_name\fP [\fBname_len\fP]"
.br
.ti -1c
.RI "ImVec3 \fB_pos\fP"
.br
.ti -1c
.RI "bool \fB_visible\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
define the property data block
.br

.SH "Constructor & Destructor Documentation"
.PP 
.SS "base_ui_component::internal_property::internal_property ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char base_ui_component::internal_property::_name[\fBname_len\fP]"

.SS "ImVec3 base_ui_component::internal_property::_pos"

.SS "bool base_ui_component::internal_property::_visible"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
