.TH "base_ui_component" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
base_ui_component \- \fBbase_ui_component\fP is the base class of control class 
.br
description: \fBbase_ui_component\fP is designed as a recursive composition design pattern, including all the basic features of graphics element, such as drawing, parenting, childing and identity,  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <control_common_def\&.h>\fP
.PP
Inherited by \fBft_base\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBinternal_property\fP"
.br
.RI "\fIdefine the property data block
.br
\fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdraw_peroperty_page\fP ()=0"
.br
.RI "\fIdraw property on the property page for editing \fP"
.ti -1c
.RI "bool \fBis_selected\fP ()"
.br
.ti -1c
.RI "void \fBset_selected\fP (bool beselected)"
.br
.ti -1c
.RI "virtual bool \fBinit_from_json\fP (Value &jvalue)"
.br
.RI "\fIinstancing class from a json value unit \fP"
.ti -1c
.RI "virtual bool \fBinit_json_unit\fP (Value &junit)"
.br
.RI "\fIinit a json unit by some data members \fP"
.ti -1c
.RI "virtual void \fBdraw\fP ()=0"
.br
.RI "\fIdraw self on a surface \fP"
.ti -1c
.RI "virtual int \fBcollect_property_range\fP (\fBvproperty_list\fP &vplist)"
.br
.RI "\fIget the memory range of the property data block \fP"
.ti -1c
.RI "virtual \fBbase_ui_component\fP * \fBget_copy_of_object\fP ()"
.br
.RI "\fIget a copy of a ui component object \fP"
.ti -1c
.RI "void \fBset_name\fP (string &name)"
.br
.ti -1c
.RI "string \fBget_name\fP ()"
.br
.ti -1c
.RI "virtual bool \fBhandle_mouse\fP ()"
.br
.ti -1c
.RI "\fBbase_ui_component\fP ()"
.br
.ti -1c
.RI "virtual \fB~base_ui_component\fP ()"
.br
.ti -1c
.RI "void \fBadd_child\fP (\fBbase_ui_component\fP *pchild)"
.br
.ti -1c
.RI "void \fBremove_child\fP (\fBbase_ui_component\fP *pchild)"
.br
.ti -1c
.RI "\fBbase_ui_component\fP * \fBget_child\fP (int index)"
.br
.ti -1c
.RI "size_t \fBget_child_count\fP ()"
.br
.ti -1c
.RI "\fBbase_ui_component\fP * \fBget_parent\fP ()"
.br
.ti -1c
.RI "size_t \fBchild_count\fP ()"
.br
.ti -1c
.RI "ImVec3 \fBbase_pos\fP ()"
.br
.RI "\fIget relative coordinates of current object \fP"
.ti -1c
.RI "ImVec3 \fBabsolute_coordinate_of_base_pos\fP ()"
.br
.RI "\fIget absolute coordinates of current object \fP"
.ti -1c
.RI "void \fBoffset\fP (ImVec2 &imof)"
.br
.ti -1c
.RI "bool \fBis_visible\fP ()"
.br
.ti -1c
.RI "void \fBset_visible\fP (bool visible)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static float \fBscreenw\fP = 0\&.0f"
.br
.ti -1c
.RI "static float \fBscreenh\fP = 0\&.0f"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBinternal_property\fP \fB_in_p\fP"
.br
.RI "\fIthe member will be serialized \fP"
.ti -1c
.RI "vector< \fBbase_ui_component\fP * > \fB_vchilds\fP"
.br
.ti -1c
.RI "\fBbase_ui_component\fP * \fB_parent\fP"
.br
.ti -1c
.RI "bool \fB_selected\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBbase_ui_component\fP * \fBfind_a_uc_from_uc\fP (\fBbase_ui_component\fP &tar_ui, const char *uname)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBbase_ui_component\fP is the base class of control class 
.br
description: \fBbase_ui_component\fP is designed as a recursive composition design pattern, including all the basic features of graphics element, such as drawing, parenting, childing and identity, 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "base_ui_component::base_ui_component ()\fC [inline]\fP"

.SS "virtual base_ui_component::~base_ui_component ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "ImVec3 base_ui_component::absolute_coordinate_of_base_pos ()\fC [inline]\fP"

.PP
get absolute coordinates of current object 
.SS "void base_ui_component::add_child (\fBbase_ui_component\fP * pchild)\fC [inline]\fP"

.SS "ImVec3 base_ui_component::base_pos ()\fC [inline]\fP"

.PP
get relative coordinates of current object 
.SS "size_t base_ui_component::child_count ()\fC [inline]\fP"

.SS "virtual int base_ui_component::collect_property_range (\fBvproperty_list\fP & vplist)\fC [inline]\fP, \fC [virtual]\fP"

.PP
get the memory range of the property data block 
.PP
\fBParameters:\fP
.RS 4
\fIvplist[out]\fP a container which the range of property data block will store into 
.RE
.PP
\fBReturns:\fP
.RS 4
length of property data block
.IP "\(bu" 2

.PP
.RE
.PP

.PP
Reimplemented in \fBft_slider\fP, \fBft_model\fP, \fBft_scene3d\fP, \fBft_cube\fP, \fBft_textblock\fP, \fBft_image\fP, \fBft_button\fP, and \fBft_listbox\fP\&.
.SS "virtual void base_ui_component::draw ()\fC [pure virtual]\fP"

.PP
draw self on a surface 
.PP
Implemented in \fBft_slider\fP, \fBft_model\fP, \fBft_cube\fP, \fBft_textblock\fP, \fBft_scene3d\fP, \fBft_image\fP, \fBft_listbox\fP, \fBft_particles_gravity\fP, \fBft_button\fP, \fBft_base\fP, \fBft_trajectory_box\fP, and \fBft_polygon_image\fP\&.
.SS "virtual void base_ui_component::draw_peroperty_page ()\fC [pure virtual]\fP"

.PP
draw property on the property page for editing 
.PP
Implemented in \fBft_slider\fP, \fBft_model\fP, \fBft_textblock\fP, \fBft_scene3d\fP, \fBft_cube\fP, \fBft_image\fP, \fBft_button\fP, \fBft_listbox\fP, \fBft_base\fP, \fBft_trajectory_box\fP, and \fBft_polygon_image\fP\&.
.SS "\fBbase_ui_component\fP* base_ui_component::get_child (int index)\fC [inline]\fP"

.SS "size_t base_ui_component::get_child_count ()\fC [inline]\fP"

.SS "virtual \fBbase_ui_component\fP* base_ui_component::get_copy_of_object ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
get a copy of a ui component object 
.PP
Reimplemented in \fBft_base\fP\&.
.SS "string base_ui_component::get_name ()\fC [inline]\fP"

.SS "\fBbase_ui_component\fP* base_ui_component::get_parent ()\fC [inline]\fP"

.SS "virtual bool base_ui_component::handle_mouse ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBft_slider\fP, \fBft_scene3d\fP, \fBft_button\fP, \fBft_listbox\fP, \fBft_base\fP, \fBft_trajectory_box\fP, and \fBft_polygon_image\fP\&.
.SS "virtual bool base_ui_component::init_from_json (Value & jvalue)\fC [inline]\fP, \fC [virtual]\fP"

.PP
instancing class from a json value unit 
.PP
\fBParameters:\fP
.RS 4
\fIjvalue\fP a json value jvalue which contain all the value of the data member of current object 
.RE
.PP
\fBReturns:\fP
.RS 4
result --true success --false failure 
.RE
.PP

.PP
Reimplemented in \fBft_slider\fP, \fBft_model\fP, \fBft_textblock\fP, \fBft_scene3d\fP, \fBft_cube\fP, \fBft_image\fP, \fBft_button\fP, \fBft_listbox\fP, \fBft_base\fP, \fBft_trajectory_box\fP, and \fBft_polygon_image\fP\&.
.SS "virtual bool base_ui_component::init_json_unit (Value & junit)\fC [inline]\fP, \fC [virtual]\fP"

.PP
init a json unit by some data members 
.PP
\fBParameters:\fP
.RS 4
\fIjunit\fP a json value junit which will be stored all the value of the data member of current object 
.RE
.PP
\fBReturns:\fP
.RS 4
result -true success -false failure 
.RE
.PP

.PP
Reimplemented in \fBft_slider\fP, \fBft_model\fP, \fBft_textblock\fP, \fBft_scene3d\fP, \fBft_cube\fP, \fBft_image\fP, and \fBft_base\fP\&.
.SS "bool base_ui_component::is_selected ()\fC [inline]\fP"

.SS "bool base_ui_component::is_visible ()\fC [inline]\fP"

.SS "void base_ui_component::offset (ImVec2 & imof)\fC [inline]\fP"

.SS "void base_ui_component::remove_child (\fBbase_ui_component\fP * pchild)\fC [inline]\fP"

.SS "void base_ui_component::set_name (string & name)\fC [inline]\fP"

.SS "void base_ui_component::set_selected (bool beselected)\fC [inline]\fP"

.SS "void base_ui_component::set_visible (bool visible)\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBbase_ui_component\fP* find_a_uc_from_uc (\fBbase_ui_component\fP & tar_ui, const char * uname)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBinternal_property\fP base_ui_component::_in_p\fC [protected]\fP"

.PP
the member will be serialized 
.SS "\fBbase_ui_component\fP* base_ui_component::_parent\fC [protected]\fP"
the parent object, this member will NULL if current object is root 
.SS "bool base_ui_component::_selected\fC [protected]\fP"
used for selecting a object in project edit for property editing 
.SS "vector<\fBbase_ui_component\fP*> base_ui_component::_vchilds\fC [protected]\fP"
the member contain all of the components which is the object of the child class of base_ui_componnet 
.SS "float base_ui_component::screenh = 0\&.0f\fC [static]\fP"
define the height of screen 
.SS "float base_ui_component::screenw = 0\&.0f\fC [static]\fP"
define the width of screen 

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
