.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/basic3d.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/basic3d.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'basic3d\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "Factory< \fBbasic_shader\fP > & \fBget_shader_fc\fP ()"
.br
.ti -1c
.RI "void \fBinstantiating_internal_shader\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBattr_size\fP [\fBen_attr_type_count\fP]"
.br
.ti -1c
.RI "map< string, vector< unique_ptr< \fBbasic_shader\fP > > > \fBg_shader_list\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Factory<\fBbasic_shader\fP>& get_shader_fc ()"

.SS "void instantiating_internal_shader ()"

.SH "Variable Documentation"
.PP 
.SS "int attr_size[\fBen_attr_type_count\fP]"
\fBInitial value:\fP
.PP
.nf
=
{
    
    1,
    
    2,
    
    3,
    
    4,
}
.fi
.SS "map<string, vector<unique_ptr<\fBbasic_shader\fP> > > g_shader_list"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
