.TH "Camera" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camera \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <camera\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP (glm::vec3 pos=glm::vec3(0\&.0, 0\&.0, 2\&.0), glm::vec3 \fBup\fP=glm::vec3(0\&.0, 1\&.0, 0\&.0), GLfloat yaw=\fBYAW\fP, GLfloat pitch=\fBPITCH\fP)"
.br
.ti -1c
.RI "glm::mat4 \fBgetViewMatrix\fP ()"
.br
.ti -1c
.RI "void \fBhandleKeyPress\fP (\fBCamera_Movement\fP direction, GLfloat deltaTime)"
.br
.ti -1c
.RI "void \fBhandleMouseMove\fP (GLfloat xoffset, GLfloat yoffset)"
.br
.ti -1c
.RI "void \fBhandleMouseScroll\fP (GLfloat yoffset)"
.br
.ti -1c
.RI "void \fBnormalizeAngle\fP ()"
.br
.ti -1c
.RI "void \fBupdateCameraVectors\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBforward\fP"
.br
.ti -1c
.RI "glm::vec3 \fBup\fP"
.br
.ti -1c
.RI "glm::vec3 \fBside\fP"
.br
.ti -1c
.RI "glm::vec3 \fBviewUp\fP"
.br
.ti -1c
.RI "glm::vec3 \fBposition\fP"
.br
.ti -1c
.RI "GLfloat \fByawAngle\fP"
.br
.ti -1c
.RI "GLfloat \fBpitchAngle\fP"
.br
.ti -1c
.RI "GLfloat \fBmoveSpeed\fP"
.br
.ti -1c
.RI "GLfloat \fBmouse_sensitivity\fP"
.br
.ti -1c
.RI "GLfloat \fBmouse_zoom\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Camera::Camera (glm::vec3 pos = \fCglm::vec3(0\&.0, 0\&.0, 2\&.0)\fP, glm::vec3 up = \fCglm::vec3(0\&.0, 1\&.0, 0\&.0)\fP, GLfloat yaw = \fC\fBYAW\fP\fP, GLfloat pitch = \fC\fBPITCH\fP\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "glm::mat4 Camera::getViewMatrix ()\fC [inline]\fP"

.SS "void Camera::handleKeyPress (\fBCamera_Movement\fP direction, GLfloat deltaTime)\fC [inline]\fP"

.SS "void Camera::handleMouseMove (GLfloat xoffset, GLfloat yoffset)\fC [inline]\fP"

.SS "void Camera::handleMouseScroll (GLfloat yoffset)\fC [inline]\fP"

.SS "void Camera::normalizeAngle ()\fC [inline]\fP"

.SS "void Camera::updateCameraVectors ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 Camera::forward"

.SS "GLfloat Camera::mouse_sensitivity"

.SS "GLfloat Camera::mouse_zoom"

.SS "GLfloat Camera::moveSpeed"

.SS "GLfloat Camera::pitchAngle"

.SS "glm::vec3 Camera::position"

.SS "glm::vec3 Camera::side"

.SS "glm::vec3 Camera::up"

.SS "glm::vec3 Camera::viewUp"

.SS "GLfloat Camera::yawAngle"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
