.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/camera.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/camera.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <GL/gl3w\&.h>\fP
.br
\fC#include <glm\&.hpp>\fP
.br
\fC#include <gtc/matrix_transform\&.hpp>\fP
.br
\fC#include <gtx/string_cast\&.hpp>\fP
.br
\fC#include <iomanip>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCamera\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCamera_Movement\fP { \fBFORWARD\fP, \fBBACKWARD\fP, \fBLEFT\fP, \fBRIGHT\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const GLfloat \fBYAW\fP = 0\&.0f"
.br
.ti -1c
.RI "const GLfloat \fBPITCH\fP = 0\&.0f"
.br
.ti -1c
.RI "const GLfloat \fBSPEED\fP = 3\&.0f"
.br
.ti -1c
.RI "const GLfloat \fBMOUSE_SENSITIVTY\fP = 0\&.05f"
.br
.ti -1c
.RI "const GLfloat \fBMOUSE_ZOOM\fP = 45\&.0f"
.br
.ti -1c
.RI "const float \fBMAX_PITCH_ANGLE\fP = 89\&.0f"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCamera_Movement\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFORWARD \fP\fP
.TP
\fB\fIBACKWARD \fP\fP
.TP
\fB\fILEFT \fP\fP
.TP
\fB\fIRIGHT \fP\fP
.SH "Variable Documentation"
.PP 
.SS "const float MAX_PITCH_ANGLE = 89\&.0f"

.SS "const GLfloat MOUSE_SENSITIVTY = 0\&.05f"

.SS "const GLfloat MOUSE_ZOOM = 45\&.0f"

.SS "const GLfloat PITCH = 0\&.0f"

.SS "const GLfloat SPEED = 3\&.0f"

.SS "const GLfloat YAW = 0\&.0f"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
