.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/common_functions.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/common_functions.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'common_functions\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'SOIL\&.h'\fP
.br
\fC#include 'texture\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ImVec2 \fBrotate_point_by_zaxis\fP (ImVec2 &tar, float angle, ImVec2 &basePoint)"
.br
.ti -1c
.RI "bool \fBprepareFBO1\fP (GLuint &colorTextId, GLuint &depthStencilTextId, GLuint &fboId, GLuint frame_width, GLuint frame_height)"
.br
.ti -1c
.RI "bool \fBaf_prepareFBO1\fP (GLuint &colorTextId, GLuint &depthStencilTextId, GLuint &fboId, GLuint frame_width, GLuint frame_height)"
.br
.ti -1c
.RI "bool \fBframe_buffer\fP ()"
.br
.ti -1c
.RI "bool \fBprepareFBO2\fP (GLuint &textId, GLuint &fboId, GLuint frame_width, GLuint frame_height)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool af_prepareFBO1 (GLuint & colorTextId, GLuint & depthStencilTextId, GLuint & fboId, GLuint frame_width, GLuint frame_height)"

.SS "bool frame_buffer ()"

.SS "bool prepareFBO1 (GLuint & colorTextId, GLuint & depthStencilTextId, GLuint & fboId, GLuint frame_width, GLuint frame_height)"

.SS "bool prepareFBO2 (GLuint & textId, GLuint & fboId, GLuint frame_width, GLuint frame_height)"

.SS "ImVec2 rotate_point_by_zaxis (ImVec2 & tar, float angle, ImVec2 & basePoint)"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
