.TH "CustomRenderTranslation::RenderTransformation" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomRenderTranslation::RenderTransformation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <renderTransform\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBScale\fP"
.br
.ti -1c
.RI "glm::vec3 \fBRotation\fP"
.br
.ti -1c
.RI "glm::vec3 \fBTranslation\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 CustomRenderTranslation::RenderTransformation::Rotation"

.SS "glm::vec3 CustomRenderTranslation::RenderTransformation::Scale"

.SS "glm::vec3 CustomRenderTranslation::RenderTransformation::Translation"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
