.TH "factory" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
factory \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <factory\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBregister_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbase_ui_component\fP * \fBproduce\fP (const std::string &key)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBbase_ui_component\fP * \fBproduce\fP (const std::string &key, Args &&\&.\&.\&.args)"
.br
.ti -1c
.RI "std::unique_ptr< \fBbase_ui_component\fP > \fBproduce_unique\fP (const std::string &key)"
.br
.ti -1c
.RI "std::shared_ptr< \fBbase_ui_component\fP > \fBproduce_shared\fP (const std::string &key)"
.br
.ti -1c
.RI "void \fBiterate_types\fP (function< void(string, function< \fBbase_ui_component\fP *()>)> imp)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBfactory\fP & \fBget\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBfactory\fP ()"
.br
.ti -1c
.RI "\fBfactory\fP (const \fBfactory\fP &)=delete"
.br
.ti -1c
.RI "\fBfactory\fP (\fBfactory\fP &&)=delete"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::map< std::string, std::function< \fBbase_ui_component\fP *()> > \fBmap_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "factory::factory ()\fC [inline]\fP, \fC [private]\fP"

.SS "factory::factory (const \fBfactory\fP &)\fC [private]\fP, \fC [delete]\fP"

.SS "factory::factory (\fBfactory\fP &&)\fC [private]\fP, \fC [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static \fBfactory\fP& factory::get ()\fC [inline]\fP, \fC [static]\fP"

.SS "void factory::iterate_types (function< void(string, function< \fBbase_ui_component\fP *()>)> imp)\fC [inline]\fP"

.SS "\fBbase_ui_component\fP* factory::produce (const std::string & key)\fC [inline]\fP"

.SS "template<typename\&.\&.\&. Args> \fBbase_ui_component\fP* factory::produce (const std::string & key, Args &&\&.\&.\&. args)\fC [inline]\fP"

.SS "std::shared_ptr<\fBbase_ui_component\fP> factory::produce_shared (const std::string & key)\fC [inline]\fP"

.SS "std::unique_ptr<\fBbase_ui_component\fP> factory::produce_unique (const std::string & key)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::map<std::string, std::function<\fBbase_ui_component\fP*()> > factory::map_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
