.TH "factory::register_t< T >" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
factory::register_t< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <factory\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBregister_t\fP (const std::string &key)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBregister_t\fP (const std::string &key, Args\&.\&.\&.args)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBfactory::register_t\fP< T >::\fBregister_t\fP (const std::string & key)\fC [inline]\fP"

.SS "template<typename T > template<typename\&.\&.\&. Args> \fBfactory::register_t\fP< T >::\fBregister_t\fP (const std::string & key, Args\&.\&.\&. args)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
