.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ft_base.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ft_base.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'factory\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBft_base\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBproperty_copy\fP (\fBvproperty_list\fP &vdest, \fBvproperty_list\fP &vsource)"
.br
.RI "\fIcopy the list of the property data block of a ui component object to another \fP"
.ti -1c
.RI "\fBbase_ui_component\fP * \fBget_copy_of_object\fP (\fBbase_ui_component\fP *byobject)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBbase_ui_component\fP* get_copy_of_object (\fBbase_ui_component\fP * byobject)"

.SS "void property_copy (\fBvproperty_list\fP & vdest, \fBvproperty_list\fP & vsource)"

.PP
copy the list of the property data block of a ui component object to another 
.PP
\fBParameters:\fP
.RS 4
\fIvdest\fP destination 
.br
\fIvsource\fP source -#vdest and vsource must have same size 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
