.TH "ft_button::intl_pt" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_button::intl_pt \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_texture_indices\fP [2]"
.br
.ti -1c
.RI "char \fB_label\fP [FILENAME_MAX]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char ft_button::intl_pt::_label[FILENAME_MAX]"

.SS "int ft_button::intl_pt::_texture_indices[2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
