.TH "ft_cube::intl_pt" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_cube::intl_pt \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBintl_pt\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImVec3 \fB_translation\fP"
.br
.ti -1c
.RI "ImVec3 \fB_scale\fP"
.br
.ti -1c
.RI "ImVec3 \fB_rotation\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ft_cube::intl_pt::intl_pt ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "ImVec3 ft_cube::intl_pt::_rotation"

.SS "ImVec3 ft_cube::intl_pt::_scale"

.SS "ImVec3 ft_cube::intl_pt::_translation"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
