.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ft_image.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ft_image.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ft_image\&.h'\fP
.br
\fC#include 'res_output\&.h'\fP
.br
\fC#include <glm\&.hpp>\fP
.br
\fC#include <gtc/matrix_transform\&.hpp>\fP
.br
\fC#include <gtc/type_ptr\&.hpp>\fP
.br
\fC#include 'common_functions\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBShowHelpMarker\fP (const char *desc)"
.br
.ti -1c
.RI "static bool \fBget_texture_item\fP (void *data, int idx, const char **out_str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static bool get_texture_item (void * data, int idx, const char ** out_str)\fC [static]\fP"

.SS "static void ShowHelpMarker (const char * desc)\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
