.TH "ft_image::intl_pt" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_image::intl_pt \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBintl_pt\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImVec2 \fB_size\fP"
.br
.ti -1c
.RI "ImVec2 \fB_axis_pos\fP"
.br
.ti -1c
.RI "int \fB_texture_index\fP"
.br
.ti -1c
.RI "float \fB_angle\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ft_image::intl_pt::intl_pt ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float ft_image::intl_pt::_angle"

.SS "ImVec2 ft_image::intl_pt::_axis_pos"

.SS "ImVec2 ft_image::intl_pt::_size"

.SS "int ft_image::intl_pt::_texture_index"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
