.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ft_model.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ft_model.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ft_model\&.h'\fP
.br
\fC#include 'SOIL\&.h'\fP
.br
\fC#include 'texture\&.h'\fP
.br
\fC#include <chrono>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBg_cureent_project_file_path\fP"
.br
.ti -1c
.RI "const char * \fBmesh_fold\fP = 'mesh_res\\\\'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string g_cureent_project_file_path"

.SS "const char* mesh_fold = 'mesh_res\\\\'"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
