.TH "ft_model::intl_pt" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_model::intl_pt \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBintl_pt\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImVec3 \fB_scale\fP"
.br
.ti -1c
.RI "ImVec3 \fB_rotation\fP"
.br
.ti -1c
.RI "ImVec3 \fB_translation\fP"
.br
.ti -1c
.RI "char \fB_texture_file\fP [\fBFILE_NAME_LEN\fP]"
.br
.ti -1c
.RI "char \fB_mesh_data_file\fP [\fBFILE_NAME_LEN\fP]"
.br
.ti -1c
.RI "GLuint \fB_textureId\fP"
.br
.ti -1c
.RI "int \fB_txt_width\fP"
.br
.ti -1c
.RI "int \fB_txt_height\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ft_model::intl_pt::intl_pt ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char ft_model::intl_pt::_mesh_data_file[\fBFILE_NAME_LEN\fP]"

.SS "ImVec3 ft_model::intl_pt::_rotation"

.SS "ImVec3 ft_model::intl_pt::_scale"

.SS "char ft_model::intl_pt::_texture_file[\fBFILE_NAME_LEN\fP]"

.SS "GLuint ft_model::intl_pt::_textureId"

.SS "ImVec3 ft_model::intl_pt::_translation"

.SS "int ft_model::intl_pt::_txt_height"

.SS "int ft_model::intl_pt::_txt_width"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
