.TH "ft_particles_gravity" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_particles_gravity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ft_particles_gravity\&.h>\fP
.PP
Inherits \fBft_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBft_particles_gravity\fP ()"
.br
.ti -1c
.RI "\fB~ft_particles_gravity\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.RI "\fIdraw self on a surface \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "GLuint \fB_vbo_uv\fP"
.br
.ti -1c
.RI "GLuint \fB_vbo_pos\fP"
.br
.ti -1c
.RI "GLuint \fB_vbo_color\fP"
.br
.ti -1c
.RI "GLuint \fB_txt_unit\fP"
.br
.ti -1c
.RI "GLuint \fB_vao\fP"
.br
.ti -1c
.RI "shared_ptr< \fBaf_shader\fP > \fB_particle_shader\fP"
.br
.ti -1c
.RI "double \fBlastTime\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ft_particles_gravity::ft_particles_gravity ()"

.SS "ft_particles_gravity::~ft_particles_gravity ()"

.SH "Member Function Documentation"
.PP 
.SS "void ft_particles_gravity::draw ()\fC [virtual]\fP"

.PP
draw self on a surface 
.PP
Reimplemented from \fBft_base\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "shared_ptr<\fBaf_shader\fP> ft_particles_gravity::_particle_shader\fC [private]\fP"

.SS "GLuint ft_particles_gravity::_txt_unit\fC [private]\fP"

.SS "GLuint ft_particles_gravity::_vao\fC [private]\fP"

.SS "GLuint ft_particles_gravity::_vbo_color\fC [private]\fP"

.SS "GLuint ft_particles_gravity::_vbo_pos\fC [private]\fP"

.SS "GLuint ft_particles_gravity::_vbo_uv\fC [private]\fP"

.SS "double ft_particles_gravity::lastTime\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
