.TH "ft_polygon_image" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_polygon_image \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ft_polygon_image\&.h>\fP
.PP
Inherits \fBft_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.RI "\fIdraw self on a surface \fP"
.ti -1c
.RI "void \fBdraw_peroperty_page\fP ()"
.br
.RI "\fIdraw property on the property page for editing \fP"
.ti -1c
.RI "bool \fBinit_from_json\fP (Value &jvalue)"
.br
.RI "\fIinstancing class from a json value unit \fP"
.ti -1c
.RI "bool \fBhandle_mouse\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "ImVector< \fBft_vertex\fP > \fB_vertexes\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void ft_polygon_image::draw ()\fC [virtual]\fP"

.PP
draw self on a surface 
.PP
Reimplemented from \fBft_base\fP\&.
.SS "void ft_polygon_image::draw_peroperty_page ()\fC [virtual]\fP"

.PP
draw property on the property page for editing 
.PP
Reimplemented from \fBft_base\fP\&.
.SS "bool ft_polygon_image::handle_mouse ()\fC [virtual]\fP"

.PP
Reimplemented from \fBft_base\fP\&.
.SS "bool ft_polygon_image::init_from_json (Value & jvalue)\fC [virtual]\fP"

.PP
instancing class from a json value unit 
.PP
\fBParameters:\fP
.RS 4
\fIjvalue\fP a json value jvalue which contain all the value of the data member of current object 
.RE
.PP
\fBReturns:\fP
.RS 4
result --true success --false failure 
.RE
.PP

.PP
Reimplemented from \fBft_base\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ImVector<\fBft_vertex\fP> ft_polygon_image::_vertexes\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
