.TH "ft_plane" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_plane \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ft_plane\&.h>\fP
.PP
Inherits \fBft_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBft_plane\fP ()"
.br
.ti -1c
.RI "\fB~ft_plane\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ft_plane::ft_plane ()"

.SS "ft_plane::~ft_plane ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
