.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ft_slider.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ft_slider.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'ft_slider\&.h'\fP
.br
\fC#include 'res_output\&.h'\fP
.br
\fC#include 'common_functions\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBARRAY_COUNT_DIRECTION_ITEM\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBShowHelpMarker\fP (const char *desc)"
.br
.ti -1c
.RI "static bool \fBget_texture_item\fP (void *data, int idx, const char **out_str)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char *const \fBdirection_iitem\fP [\fBARRAY_COUNT_DIRECTION_ITEM\fP] = { 'x', 'y', 'custom'}"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARRAY_COUNT_DIRECTION_ITEM   3"

.SH "Function Documentation"
.PP 
.SS "static bool get_texture_item (void * data, int idx, const char ** out_str)\fC [static]\fP"

.SS "static void ShowHelpMarker (const char * desc)\fC [static]\fP"

.SH "Variable Documentation"
.PP 
.SS "const char* const direction_iitem[\fBARRAY_COUNT_DIRECTION_ITEM\fP] = { 'x', 'y', 'custom'}"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
