.TH "ft_slider::random_point_array" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_slider::random_point_array \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrandom_point_array\fP ()"
.br
.ti -1c
.RI "\fBrandom_point_array\fP (ImVec2 &itop, ImVec2 &ibottom)"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBrandom_point_array\fP &it)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBrandom_point_array\fP &it)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImVec2 \fBtop_point\fP"
.br
.ti -1c
.RI "ImVec2 \fBbottom_point\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ft_slider::random_point_array::random_point_array ()\fC [inline]\fP"

.SS "ft_slider::random_point_array::random_point_array (ImVec2 & itop, ImVec2 & ibottom)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ft_slider::random_point_array::operator= (\fBrandom_point_array\fP & it)\fC [inline]\fP"

.SS "bool ft_slider::random_point_array::operator== (\fBrandom_point_array\fP & it)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "ImVec2 ft_slider::random_point_array::bottom_point"

.SS "ImVec2 ft_slider::random_point_array::top_point"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
