.TH "ft_scene3d::intl_pt" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_scene3d::intl_pt \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBintl_pt\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImVec2 \fB_size\fP"
.br
.ti -1c
.RI "ImVec4 \fB_back_color\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ft_scene3d::intl_pt::intl_pt ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "ImVec4 ft_scene3d::intl_pt::_back_color"

.SS "ImVec2 ft_scene3d::intl_pt::_size"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
