.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ft_scene3d.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ft_scene3d.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ft_base\&.h'\fP
.br
\fC#include <glm\&.hpp>\fP
.br
\fC#include <gtc/matrix_transform\&.hpp>\fP
.br
\fC#include <gtc/type_ptr\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBft_scene3d\fP"
.br
.ti -1c
.RI "struct \fBft_scene3d::intl_pt\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
