.TH "ft_sphere" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_sphere \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ft_sphere\&.h>\fP
.PP
Inherits \fBft_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBft_sphere\fP ()"
.br
.ti -1c
.RI "\fB~ft_sphere\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ft_sphere::ft_sphere ()"

.SS "ft_sphere::~ft_sphere ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
