.TH "ft_slider::intl_pt" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_slider::intl_pt \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fB_position\fP {0\&.f}"
.br
.ti -1c
.RI "int \fB_direction_item\fP { 0 }"
.br
.ti -1c
.RI "ImVec2 \fB_bg_axi_pos\fP"
.br
.ti -1c
.RI "float \fB_bg_angle\fP {0\&.f}"
.br
.ti -1c
.RI "int \fB_texture_bg_index\fP {0}"
.br
.ti -1c
.RI "ImVec2 \fB_head_pos\fP"
.br
.ti -1c
.RI "int \fB_texture_head_index\fP {0}"
.br
.ti -1c
.RI "ImVec2 \fB_thumb_pos\fP"
.br
.ti -1c
.RI "int \fB_texture_thumb_index\fP {0}"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float ft_slider::intl_pt::_bg_angle {0\&.f}"

.SS "ImVec2 ft_slider::intl_pt::_bg_axi_pos"

.SS "int ft_slider::intl_pt::_direction_item { 0 }"

.SS "ImVec2 ft_slider::intl_pt::_head_pos"

.SS "float ft_slider::intl_pt::_position {0\&.f}"

.SS "int ft_slider::intl_pt::_texture_bg_index {0}"

.SS "int ft_slider::intl_pt::_texture_head_index {0}"

.SS "int ft_slider::intl_pt::_texture_thumb_index {0}"

.SS "ImVec2 ft_slider::intl_pt::_thumb_pos"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
