.TH "ft_slider" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_slider \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ft_slider\&.h>\fP
.PP
Inherits \fBft_base\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBintl_pt\fP"
.br
.ti -1c
.RI "struct \fBrandom_point_array\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBft_slider\fP ()"
.br
.ti -1c
.RI "int \fBcollect_property_range\fP (\fBvproperty_list\fP &vplist)"
.br
.RI "\fIget the memory range of the property data block \fP"
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.RI "\fIdraw self on a surface \fP"
.ti -1c
.RI "void \fBdraw_peroperty_page\fP ()"
.br
.RI "\fIdraw property on the property page for editing \fP"
.ti -1c
.RI "bool \fBinit_from_json\fP (Value &jvalue)"
.br
.RI "\fIinstancing class from a json value unit \fP"
.ti -1c
.RI "bool \fBinit_json_unit\fP (Value &junit)"
.br
.RI "\fIinit a json unit by some data members \fP"
.ti -1c
.RI "bool \fBhandle_mouse\fP ()"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "typedef std::vector< \fBrandom_point_array\fP > \fBrandom_point_vec\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fBread_point_position_file\fP (const char *str)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBintl_pt\fP \fB_slider_pt\fP"
.br
.ti -1c
.RI "ImVec2 \fB_bg_texture_size\fP"
.br
.ti -1c
.RI "ImVec2 \fB_head_texture_size\fP"
.br
.ti -1c
.RI "ImVec2 \fB_thumb_texture_size\fP"
.br
.ti -1c
.RI "char \fB_cbuffer_random_text\fP [128]"
.br
.ti -1c
.RI "\fBrandom_point_vec\fP \fBft_slider_random_point_vec\fP"
.br
.ti -1c
.RI "float \fB_random_all_length\fP {0\&.f}"
.br
.ti -1c
.RI "\fBrandom_point_array\fP \fB_pre_point_2vec2\fP"
.br
.ti -1c
.RI "\fBrandom_point_array\fP \fB_next_point_2vec2\fP"
.br
.ti -1c
.RI "\fBrandom_point_array\fP \fB_current_point_2vec2_thumb_use\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::vector<\fBrandom_point_array\fP> \fBft_slider::random_point_vec\fP\fC [private]\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ft_slider::ft_slider ()"

.SH "Member Function Documentation"
.PP 
.SS "int ft_slider::collect_property_range (\fBvproperty_list\fP & vplist)\fC [inline]\fP, \fC [virtual]\fP"

.PP
get the memory range of the property data block 
.PP
\fBParameters:\fP
.RS 4
\fIvplist[out]\fP a container which the range of property data block will store into 
.RE
.PP
\fBReturns:\fP
.RS 4
length of property data block
.IP "\(bu" 2

.PP
.RE
.PP

.PP
Reimplemented from \fBbase_ui_component\fP\&.
.SS "void ft_slider::draw ()\fC [virtual]\fP"

.PP
draw self on a surface 
.PP
Reimplemented from \fBft_base\fP\&.
.SS "void ft_slider::draw_peroperty_page ()\fC [virtual]\fP"

.PP
draw property on the property page for editing 
.PP
Reimplemented from \fBft_base\fP\&.
.SS "bool ft_slider::handle_mouse ()\fC [virtual]\fP"

.PP
Reimplemented from \fBft_base\fP\&.
.SS "bool ft_slider::init_from_json (Value & jvalue)\fC [virtual]\fP"

.PP
instancing class from a json value unit 
.PP
\fBParameters:\fP
.RS 4
\fIjvalue\fP a json value jvalue which contain all the value of the data member of current object 
.RE
.PP
\fBReturns:\fP
.RS 4
result --true success --false failure 
.RE
.PP

.PP
Reimplemented from \fBft_base\fP\&.
.SS "bool ft_slider::init_json_unit (Value & junit)\fC [virtual]\fP"

.PP
init a json unit by some data members 
.PP
\fBParameters:\fP
.RS 4
\fIjunit\fP a json value junit which will be stored all the value of the data member of current object 
.RE
.PP
\fBReturns:\fP
.RS 4
result -true success -false failure 
.RE
.PP

.PP
Reimplemented from \fBft_base\fP\&.
.SS "bool ft_slider::read_point_position_file (const char * str)\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "ImVec2 ft_slider::_bg_texture_size\fC [private]\fP"

.SS "char ft_slider::_cbuffer_random_text[128]\fC [private]\fP"

.SS "\fBrandom_point_array\fP ft_slider::_current_point_2vec2_thumb_use\fC [private]\fP"

.SS "ImVec2 ft_slider::_head_texture_size\fC [private]\fP"

.SS "\fBrandom_point_array\fP ft_slider::_next_point_2vec2\fC [private]\fP"

.SS "\fBrandom_point_array\fP ft_slider::_pre_point_2vec2\fC [private]\fP"

.SS "float ft_slider::_random_all_length {0\&.f}\fC [private]\fP"

.SS "\fBintl_pt\fP ft_slider::_slider_pt\fC [private]\fP"

.SS "ImVec2 ft_slider::_thumb_texture_size\fC [private]\fP"

.SS "\fBrandom_point_vec\fP ft_slider::ft_slider_random_point_vec\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
