.TH "ft_textblock::intl_pt" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_textblock::intl_pt \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBintl_pt\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImVec4 \fB_txt_color\fP"
.br
.ti -1c
.RI "float \fB_width\fP"
.br
.ti -1c
.RI "char \fB_content\fP [\fBMAX_CONTENT_LEN\fP]"
.br
.ti -1c
.RI "bool \fB_wrapped\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ft_textblock::intl_pt::intl_pt ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char ft_textblock::intl_pt::_content[\fBMAX_CONTENT_LEN\fP]"

.SS "ImVec4 ft_textblock::intl_pt::_txt_color"

.SS "float ft_textblock::intl_pt::_width"

.SS "bool ft_textblock::intl_pt::_wrapped"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
