.TH "ft_vertex" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_vertex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <control_common_def\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImVec3 \fBpos\fP"
.br
.ti -1c
.RI "ImVec2 \fBuv\fP"
.br
.ti -1c
.RI "ImU32 \fBcol\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "ImU32 ft_vertex::col"

.SS "ImVec3 ft_vertex::pos"

.SS "ImVec2 ft_vertex::uv"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
