.TH "G:/GitHub/my_imgui/my_imgui/examples Directory Reference" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBauto_future_graphics_design\fP"
.br
.in -1c
