.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design Directory Reference" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaf_shader\&.cpp\fP"
.br
.ti -1c
.RI "file \fBaf_shader\&.h\fP"
.br
.ti -1c
.RI "file \fBafb_load\&.cpp\fP"
.br
.ti -1c
.RI "file \fBafb_load\&.h\fP"
.br
.ti -1c
.RI "file \fBafb_output\&.cpp\fP"
.br
.ti -1c
.RI "file \fBafb_output\&.h\fP"
.br
.ti -1c
.RI "file \fBbasic3d\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbasic3d\&.h\fP"
.br
.ti -1c
.RI "file \fBcamera\&.h\fP"
.br
.ti -1c
.RI "file \fBcommon_functions\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcommon_functions\&.h\fP"
.br
.ti -1c
.RI "file \fBcontrol_common_def\&.h\fP"
.br
.RI "\fIthe head file provide basic definition of control class, all control class inherited from the class \fBbase_ui_component\fP \fP"
.ti -1c
.RI "file \fBfactory\&.h\fP"
.br
.ti -1c
.RI "file \fBft_base\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_base\&.h\fP"
.br
.ti -1c
.RI "file \fBft_button\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_button\&.h\fP"
.br
.ti -1c
.RI "file \fBft_cube\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_cube\&.h\fP"
.br
.ti -1c
.RI "file \fBft_image\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_image\&.h\fP"
.br
.ti -1c
.RI "file \fBft_listbox\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_listbox\&.h\fP"
.br
.ti -1c
.RI "file \fBft_model\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_model\&.h\fP"
.br
.ti -1c
.RI "file \fBft_particles_gravity\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_particles_gravity\&.h\fP"
.br
.ti -1c
.RI "file \fBft_plane\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_plane\&.h\fP"
.br
.ti -1c
.RI "file \fBft_polygon_image\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_polygon_image\&.h\fP"
.br
.ti -1c
.RI "file \fBft_scene3d\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_scene3d\&.h\fP"
.br
.ti -1c
.RI "file \fBft_slider\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_slider\&.h\fP"
.br
.ti -1c
.RI "file \fBft_sphere\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_sphere\&.h\fP"
.br
.ti -1c
.RI "file \fBft_textblock\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_textblock\&.h\fP"
.br
.ti -1c
.RI "file \fBft_trajectory_box\&.cpp\fP"
.br
.ti -1c
.RI "file \fBft_trajectory_box\&.h\fP"
.br
.ti -1c
.RI "file \fBimgui_impl_glfw_gl3\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimgui_impl_glfw_gl3\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain_app\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmaterial\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmaterial\&.h\fP"
.br
.ti -1c
.RI "file \fBmaterial_shader_edit\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmaterial_shader_edit\&.h\fP"
.br
.ti -1c
.RI "file \fBMesh\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMesh\&.h\fP"
.br
.ti -1c
.RI "file \fBminiz\&.c\fP"
.br
.ti -1c
.RI "file \fBminiz\&.h\fP"
.br
.ti -1c
.RI "file \fBofbx\&.cpp\fP"
.br
.ti -1c
.RI "file \fBofbx\&.h\fP"
.br
.ti -1c
.RI "file \fBprimitive_object\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprimitive_object\&.h\fP"
.br
.ti -1c
.RI "file \fBproject_edit\&.cpp\fP"
.br
.ti -1c
.RI "file \fBproject_edit\&.h\fP"
.br
.ti -1c
.RI "file \fBrenderTransform\&.h\fP"
.br
.ti -1c
.RI "file \fBres_edit\&.cpp\fP"
.br
.ti -1c
.RI "file \fBres_edit\&.h\fP"
.br
.ti -1c
.RI "file \fBres_internal\&.cpp\fP"
.br
.ti -1c
.RI "file \fBres_internal\&.h\fP"
.br
.ti -1c
.RI "file \fBres_output\&.cpp\fP"
.br
.ti -1c
.RI "file \fBres_output\&.h\fP"
.br
.ti -1c
.RI "file \fBresource\&.h\fP"
.br
.ti -1c
.RI "file \fBshader_uf\&.cpp\fP"
.br
.ti -1c
.RI "file \fBshader_uf\&.h\fP"
.br
.ti -1c
.RI "file \fBtexture_res_load\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtexture_res_load\&.h\fP"
.br
.ti -1c
.RI "file \fBtexture_shader\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtexture_shader\&.h\fP"
.br
.ti -1c
.RI "file \fBui_assembler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBui_assembler\&.h\fP"
.br
.ti -1c
.RI "file \fBuser_control_imgui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBuser_control_imgui\&.h\fP"
.br
.in -1c
