.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/imgui_impl_glfw_gl3.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/imgui_impl_glfw_gl3.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "IMGUI_API bool \fBImGui_ImplGlfwGL3_Init\fP (GLFWwindow *window, bool install_callbacks, const char *glsl_version=NULL)"
.br
.ti -1c
.RI "IMGUI_API void \fBImGui_ImplGlfwGL3_Shutdown\fP ()"
.br
.ti -1c
.RI "IMGUI_API void \fBImGui_ImplGlfwGL3_NewFrame\fP ()"
.br
.ti -1c
.RI "IMGUI_API void \fBImGui_ImplGlfwGL3_RenderDrawData\fP (ImDrawData *draw_data)"
.br
.ti -1c
.RI "IMGUI_API void \fBImGui_ImplGlfwGL3_InvalidateDeviceObjects\fP ()"
.br
.ti -1c
.RI "IMGUI_API bool \fBImGui_ImplGlfwGL3_CreateDeviceObjects\fP ()"
.br
.ti -1c
.RI "IMGUI_API void \fBImGui_ImplGlfw_MouseButtonCallback\fP (GLFWwindow *window, int button, int action, int mods)"
.br
.ti -1c
.RI "IMGUI_API void \fBImGui_ImplGlfw_ScrollCallback\fP (GLFWwindow *window, double xoffset, double yoffset)"
.br
.ti -1c
.RI "IMGUI_API void \fBImGui_ImplGlfw_KeyCallback\fP (GLFWwindow *window, int key, int scancode, int action, int mods)"
.br
.ti -1c
.RI "IMGUI_API void \fBImGui_ImplGlfw_CharCallback\fP (GLFWwindow *window, unsigned int c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "IMGUI_API void ImGui_ImplGlfw_CharCallback (GLFWwindow * window, unsigned int c)"

.SS "IMGUI_API void ImGui_ImplGlfw_KeyCallback (GLFWwindow * window, int key, int scancode, int action, int mods)"

.SS "IMGUI_API void ImGui_ImplGlfw_MouseButtonCallback (GLFWwindow * window, int button, int action, int mods)"

.SS "IMGUI_API void ImGui_ImplGlfw_ScrollCallback (GLFWwindow * window, double xoffset, double yoffset)"

.SS "IMGUI_API bool ImGui_ImplGlfwGL3_CreateDeviceObjects ()"

.SS "IMGUI_API bool ImGui_ImplGlfwGL3_Init (GLFWwindow * window, bool install_callbacks, const char * glsl_version = \fCNULL\fP)"

.SS "IMGUI_API void ImGui_ImplGlfwGL3_InvalidateDeviceObjects ()"

.SS "IMGUI_API void ImGui_ImplGlfwGL3_NewFrame ()"

.SS "IMGUI_API void ImGui_ImplGlfwGL3_RenderDrawData (ImDrawData * draw_data)"

.SS "IMGUI_API void ImGui_ImplGlfwGL3_Shutdown ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
