.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/main_app.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/main_app.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'imgui\&.h'\fP
.br
\fC#include 'imgui_impl_glfw_gl3\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <GL/gl3w\&.h>\fP
.br
\fC#include <GLFW/glfw3\&.h>\fP
.br
\fC#include 'SOIL\&.h'\fP
.br
\fC#include 'texture\&.h'\fP
.br
\fC#include 'ft_base\&.h'\fP
.br
\fC#include 'res_output\&.h'\fP
.br
\fC#include 'ft_image\&.h'\fP
.br
\fC#include <functional>\fP
.br
\fC#include <windows\&.h>\fP
.br
\fC#include <locale\&.h>\fP
.br
\fC#include <ShlObj\&.h>\fP
.br
\fC#include <Commdlg\&.h>\fP
.br
\fC#include 'Resource\&.h'\fP
.br
\fC#include 'afb_load\&.h'\fP
.br
\fC#include 'primitive_object\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBerror_callback\fP (int error, const char *description)"
.br
.ti -1c
.RI "void \fBinstantiating_internal_shader\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBg_cureent_project_file_path\fP"
.br
.ti -1c
.RI "string \fBg_current_run_path\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void error_callback (int error, const char * description)\fC [static]\fP"

.SS "void instantiating_internal_shader ()"

.SS "int main (int argc, char * argv[])"

.SH "Variable Documentation"
.PP 
.SS "string g_cureent_project_file_path"

.SS "string g_current_run_path"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
