.TH "material_shader_edit" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
material_shader_edit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <material_shader_edit\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmaterial_shader_edit\fP ()"
.br
.ti -1c
.RI "\fB~material_shader_edit\fP ()"
.br
.ti -1c
.RI "void \fBload_shader\fP ()"
.br
.ti -1c
.RI "void \fBload_shader_info\fP ()"
.br
.ti -1c
.RI "void \fBdraw_shader\fP ()"
.br
.ti -1c
.RI "void \fBdraw_material\fP ()"
.br
.ti -1c
.RI "void \fBdraw_shader_item_property\fP ()"
.br
.ti -1c
.RI "void \fBdraw_material_item_property\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "material_shader_edit::material_shader_edit ()\fC [inline]\fP"

.SS "material_shader_edit::~material_shader_edit ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void material_shader_edit::draw_material ()"

.SS "void material_shader_edit::draw_material_item_property ()"

.SS "void material_shader_edit::draw_shader ()"

.SS "void material_shader_edit::draw_shader_item_property ()"

.SS "void material_shader_edit::load_shader ()"

.SS "void material_shader_edit::load_shader_info ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
