.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/material.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/material.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'material\&.h'\fP
.br
\fC#include 'user_control_imgui\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmmaterial\fP \fBg_material_list\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBmmaterial\fP g_material_list"
material of g_material_list will be referenced by some ui components 
.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
