.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/material.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/material.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'af_shader\&.h'\fP
.br
\fC#include 'shader_uf\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmaterial\fP"
.br
.RI "\fIis instance of the shader 
.br
description: \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef map< string, shared_ptr< \fBshader_uf\fP > > \fBmp_shader_uf\fP"
.br
.ti -1c
.RI "typedef map< string, shared_ptr< \fBmaterial\fP > > \fBmmaterial\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmmaterial\fP \fBg_material_list\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef map<string,shared_ptr<\fBmaterial\fP> > \fBmmaterial\fP"

.SS "typedef map<string, shared_ptr<\fBshader_uf\fP> > \fBmp_shader_uf\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBmmaterial\fP g_material_list"
material of g_material_list will be referenced by some ui components 
.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
