.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/material_shader_edit.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/material_shader_edit.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'material_shader_edit\&.h'\fP
.br
\fC#include 'af_shader\&.h'\fP
.br
\fC#include 'material\&.h'\fP
.br
\fC#include 'user_control_imgui\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFILE_NAME_LEN\fP   50"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBg_cureent_project_file_path\fP"
.br
.ti -1c
.RI "const char * \fBstr_shaders_fold\fP = 'shaders\\\\'"
.br
.ti -1c
.RI "shared_ptr< \fBaf_shader\fP > \fBpshd_sel\fP = nullptr"
.br
.ti -1c
.RI "shared_ptr< \fBmaterial\fP > \fBpmateral_sel\fP = nullptr"
.br
.ti -1c
.RI "string \fBcompile_info\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FILE_NAME_LEN   50"

.SH "Variable Documentation"
.PP 
.SS "string compile_info"

.SS "string g_cureent_project_file_path"

.SS "shared_ptr<\fBmaterial\fP> pmateral_sel = nullptr"

.SS "shared_ptr<\fBaf_shader\fP> pshd_sel = nullptr"

.SS "const char* str_shaders_fold = 'shaders\\\\'"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
