.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/material_shader_edit.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/material_shader_edit.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmaterial_shader_edit\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
