.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/Mesh.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/Mesh.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GL/gl3w\&.h>\fP
.br
\fC#include <glm\&.hpp>\fP
.br
\fC#include <gtc/matrix_transform\&.hpp>\fP
.br
\fC#include <gtx/string_cast\&.hpp>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'ofbx\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVertex\fP"
.br
.ti -1c
.RI "struct \fBVertexCombineIndex\fP"
.br
.ti -1c
.RI "class \fBObjLoader\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtransform_FBX_2_Object\fP (\fBofbx::IScene\fP &scene, std::vector< \fBVertex\fP > &vertData)"
.br
.ti -1c
.RI "void \fBloadFBXFile\fP (const char *path, std::vector< \fBVertex\fP > &vertData)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void loadFBXFile (const char * path, std::vector< \fBVertex\fP > & vertData)"

.SS "void transform_FBX_2_Object (\fBofbx::IScene\fP & scene, std::vector< \fBVertex\fP > & vertData)"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
