.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/Mesh.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/Mesh.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Mesh\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCustom_Max\fP(a,  b)   a>b?a:b"
.br
.ti -1c
.RI "#define \fBCustom_Min\fP(a,  b)   a<b?a:b"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtransform_FBX_2_Object\fP (\fBofbx::IScene\fP &scene, std::vector< \fBVertex\fP > &vertData)"
.br
.ti -1c
.RI "void \fBloadFBXFile\fP (const char *path, std::vector< \fBVertex\fP > &vertData)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define Custom_Max(a, b)   a>b?a:b"

.SS "#define Custom_Min(a, b)   a<b?a:b"

.SH "Function Documentation"
.PP 
.SS "void loadFBXFile (const char * path, std::vector< \fBVertex\fP > & vertData)"

.SS "void transform_FBX_2_Object (\fBofbx::IScene\fP & scene, std::vector< \fBVertex\fP > & vertData)"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
