.TH "mz_zip_array" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mz_zip_array \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBm_p\fP"
.br
.ti -1c
.RI "size_t \fBm_size\fP"
.br
.ti -1c
.RI "size_t \fBm_capacity\fP"
.br
.ti -1c
.RI "\fBmz_uint\fP \fBm_element_size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "size_t mz_zip_array::m_capacity"

.SS "\fBmz_uint\fP mz_zip_array::m_element_size"

.SS "void* mz_zip_array::m_p"

.SS "size_t mz_zip_array::m_size"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
