.TH "mz_zip_internal_state_tag" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mz_zip_internal_state_tag \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmz_zip_array\fP \fBm_central_dir\fP"
.br
.ti -1c
.RI "\fBmz_zip_array\fP \fBm_central_dir_offsets\fP"
.br
.ti -1c
.RI "\fBmz_zip_array\fP \fBm_sorted_central_dir_offsets\fP"
.br
.ti -1c
.RI "uint32_t \fBm_init_flags\fP"
.br
.ti -1c
.RI "\fBmz_bool\fP \fBm_zip64\fP"
.br
.ti -1c
.RI "\fBmz_bool\fP \fBm_zip64_has_extended_info_fields\fP"
.br
.ti -1c
.RI "\fBMZ_FILE\fP * \fBm_pFile\fP"
.br
.ti -1c
.RI "\fBmz_uint64\fP \fBm_file_archive_start_ofs\fP"
.br
.ti -1c
.RI "void * \fBm_pMem\fP"
.br
.ti -1c
.RI "size_t \fBm_mem_size\fP"
.br
.ti -1c
.RI "size_t \fBm_mem_capacity\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmz_zip_array\fP mz_zip_internal_state_tag::m_central_dir"

.SS "\fBmz_zip_array\fP mz_zip_internal_state_tag::m_central_dir_offsets"

.SS "\fBmz_uint64\fP mz_zip_internal_state_tag::m_file_archive_start_ofs"

.SS "uint32_t mz_zip_internal_state_tag::m_init_flags"

.SS "size_t mz_zip_internal_state_tag::m_mem_capacity"

.SS "size_t mz_zip_internal_state_tag::m_mem_size"

.SS "\fBMZ_FILE\fP* mz_zip_internal_state_tag::m_pFile"

.SS "void* mz_zip_internal_state_tag::m_pMem"

.SS "\fBmz_zip_array\fP mz_zip_internal_state_tag::m_sorted_central_dir_offsets"

.SS "\fBmz_bool\fP mz_zip_internal_state_tag::m_zip64"

.SS "\fBmz_bool\fP mz_zip_internal_state_tag::m_zip64_has_extended_info_fields"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
