.TH "ObjLoader" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjLoader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mesh\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBloadFromFile\fP (const char *path, std::vector< \fBVertex\fP > &vertData)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static bool ObjLoader::loadFromFile (const char * path, std::vector< \fBVertex\fP > & vertData)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
