.TH "ofbx::AnimationCurveNode" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::AnimationCurveNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ofbx\&.h>\fP
.PP
Inherits \fBofbx::Object\fP\&.
.PP
Inherited by \fBofbx::AnimationCurveNodeImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimationCurveNode\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "virtual \fBVec3\fP \fBgetNodeLocalTransform\fP (double time) const =0"
.br
.ti -1c
.RI "virtual const \fBObject\fP * \fBgetBone\fP () const =0"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBType\fP \fBs_type\fP = \fBType::ANIMATION_CURVE_NODE\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::AnimationCurveNode::AnimationCurveNode (const \fBScene\fP & _scene, const \fBIElement\fP & _element)"

.SH "Member Function Documentation"
.PP 
.SS "virtual const \fBObject\fP* ofbx::AnimationCurveNode::getBone () const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::AnimationCurveNodeImpl\fP\&.
.SS "virtual \fBVec3\fP ofbx::AnimationCurveNode::getNodeLocalTransform (double time) const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::AnimationCurveNodeImpl\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBType\fP ofbx::AnimationCurveNode::s_type = \fBType::ANIMATION_CURVE_NODE\fP\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
