.TH "ofbx::Error" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::Error \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBError\fP ()"
.br
.ti -1c
.RI "\fBError\fP (const char *msg)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const char * \fBs_message\fP = ''"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::Error::Error ()\fC [inline]\fP"

.SS "ofbx::Error::Error (const char * msg)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const char * ofbx::Error::s_message = ''\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
