.TH "ofbx::NodeAttribute" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::NodeAttribute \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ofbx\&.h>\fP
.PP
Inherits \fBofbx::Object\fP\&.
.PP
Inherited by \fBofbx::NodeAttributeImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeAttribute\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "virtual \fBDataView\fP \fBgetAttributeType\fP () const =0"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBType\fP \fBs_type\fP = \fBType::NODE_ATTRIBUTE\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::NodeAttribute::NodeAttribute (const \fBScene\fP & _scene, const \fBIElement\fP & _element)"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBDataView\fP ofbx::NodeAttribute::getAttributeType () const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::NodeAttributeImpl\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBType\fP ofbx::NodeAttribute::s_type = \fBType::NODE_ATTRIBUTE\fP\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
