.TH "ofbx::SkinImpl" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::SkinImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBofbx::Skin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSkinImpl\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "int \fBgetClusterCount\fP () const override"
.br
.ti -1c
.RI "const \fBCluster\fP * \fBgetCluster\fP (int idx) const override"
.br
.ti -1c
.RI "\fBType\fP \fBgetType\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBCluster\fP * > \fBclusters\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::SkinImpl::SkinImpl (const \fBScene\fP & _scene, const \fBIElement\fP & _element)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBCluster\fP* ofbx::SkinImpl::getCluster (int idx) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Skin\fP\&.
.SS "int ofbx::SkinImpl::getClusterCount () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Skin\fP\&.
.SS "\fBType\fP ofbx::SkinImpl::getType () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Object\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBCluster\fP*> ofbx::SkinImpl::clusters"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
