.TH "ofbx::Property" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::Property \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBofbx::IElementProperty\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Property\fP ()"
.br
.ti -1c
.RI "\fBType\fP \fBgetType\fP () const override"
.br
.ti -1c
.RI "\fBIElementProperty\fP * \fBgetNext\fP () const override"
.br
.ti -1c
.RI "\fBDataView\fP \fBgetValue\fP () const override"
.br
.ti -1c
.RI "int \fBgetCount\fP () const override"
.br
.ti -1c
.RI "bool \fBgetValues\fP (double *values, int max_size) const override"
.br
.ti -1c
.RI "bool \fBgetValues\fP (float *values, int max_size) const override"
.br
.ti -1c
.RI "bool \fBgetValues\fP (\fBu64\fP *values, int max_size) const override"
.br
.ti -1c
.RI "bool \fBgetValues\fP (\fBi64\fP *values, int max_size) const override"
.br
.ti -1c
.RI "bool \fBgetValues\fP (int *values, int max_size) const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBDataView\fP \fBvalue\fP"
.br
.ti -1c
.RI "\fBProperty\fP * \fBnext\fP = nullptr"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::Property::~Property ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int ofbx::Property::getCount () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::IElementProperty\fP\&.
.SS "\fBIElementProperty\fP* ofbx::Property::getNext () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::IElementProperty\fP\&.
.SS "\fBType\fP ofbx::Property::getType () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::IElementProperty\fP\&.
.SS "\fBDataView\fP ofbx::Property::getValue () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::IElementProperty\fP\&.
.SS "bool ofbx::Property::getValues (double * values, int max_size) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::IElementProperty\fP\&.
.SS "bool ofbx::Property::getValues (float * values, int max_size) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::IElementProperty\fP\&.
.SS "bool ofbx::Property::getValues (\fBu64\fP * values, int max_size) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::IElementProperty\fP\&.
.SS "bool ofbx::Property::getValues (\fBi64\fP * values, int max_size) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::IElementProperty\fP\&.
.SS "bool ofbx::Property::getValues (int * values, int max_size) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::IElementProperty\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ofbx::Property::count"

.SS "\fBProperty\fP* ofbx::Property::next = nullptr"

.SS "\fBu8\fP ofbx::Property::type"

.SS "\fBDataView\fP ofbx::Property::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
