.TH "ofbx::Matrix" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::Matrix \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ofbx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBm\fP [16]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double ofbx::Matrix::m[16]"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
