.TH "ofbx::AnimationStack" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::AnimationStack \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ofbx\&.h>\fP
.PP
Inherits \fBofbx::Object\fP\&.
.PP
Inherited by \fBofbx::AnimationStackImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimationStack\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "virtual const \fBAnimationLayer\fP * \fBgetLayer\fP (int index) const =0"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBType\fP \fBs_type\fP = \fBType::ANIMATION_STACK\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::AnimationStack::AnimationStack (const \fBScene\fP & _scene, const \fBIElement\fP & _element)"

.SH "Member Function Documentation"
.PP 
.SS "virtual const \fBAnimationLayer\fP* ofbx::AnimationStack::getLayer (int index) const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::AnimationStackImpl\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBType\fP ofbx::AnimationStack::s_type = \fBType::ANIMATION_STACK\fP\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
