.TH "ofbx::IElementProperty" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::IElementProperty \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ofbx\&.h>\fP
.PP
Inherited by \fBofbx::Property\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP : unsigned char { \fBLONG\fP = 'L', \fBINTEGER\fP = 'I', \fBSTRING\fP = 'S', \fBFLOAT\fP = 'F', \fBDOUBLE\fP = 'D', \fBARRAY_DOUBLE\fP = 'd', \fBARRAY_INT\fP = 'i', \fBARRAY_LONG\fP = 'l', \fBARRAY_FLOAT\fP = 'f' }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IElementProperty\fP ()"
.br
.ti -1c
.RI "virtual \fBType\fP \fBgetType\fP () const =0"
.br
.ti -1c
.RI "virtual \fBIElementProperty\fP * \fBgetNext\fP () const =0"
.br
.ti -1c
.RI "virtual \fBDataView\fP \fBgetValue\fP () const =0"
.br
.ti -1c
.RI "virtual int \fBgetCount\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBgetValues\fP (double *values, int max_size) const =0"
.br
.ti -1c
.RI "virtual bool \fBgetValues\fP (int *values, int max_size) const =0"
.br
.ti -1c
.RI "virtual bool \fBgetValues\fP (float *values, int max_size) const =0"
.br
.ti -1c
.RI "virtual bool \fBgetValues\fP (\fBu64\fP *values, int max_size) const =0"
.br
.ti -1c
.RI "virtual bool \fBgetValues\fP (\fBi64\fP *values, int max_size) const =0"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBofbx::IElementProperty::Type\fP : unsigned char"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILONG \fP\fP
.TP
\fB\fIINTEGER \fP\fP
.TP
\fB\fISTRING \fP\fP
.TP
\fB\fIFLOAT \fP\fP
.TP
\fB\fIDOUBLE \fP\fP
.TP
\fB\fIARRAY_DOUBLE \fP\fP
.TP
\fB\fIARRAY_INT \fP\fP
.TP
\fB\fIARRAY_LONG \fP\fP
.TP
\fB\fIARRAY_FLOAT \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ofbx::IElementProperty::~IElementProperty ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual int ofbx::IElementProperty::getCount () const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::Property\fP\&.
.SS "virtual \fBIElementProperty\fP* ofbx::IElementProperty::getNext () const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::Property\fP\&.
.SS "virtual \fBType\fP ofbx::IElementProperty::getType () const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::Property\fP\&.
.SS "virtual \fBDataView\fP ofbx::IElementProperty::getValue () const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::Property\fP\&.
.SS "virtual bool ofbx::IElementProperty::getValues (double * values, int max_size) const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::Property\fP\&.
.SS "virtual bool ofbx::IElementProperty::getValues (int * values, int max_size) const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::Property\fP\&.
.SS "virtual bool ofbx::IElementProperty::getValues (float * values, int max_size) const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::Property\fP\&.
.SS "virtual bool ofbx::IElementProperty::getValues (\fBu64\fP * values, int max_size) const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::Property\fP\&.
.SS "virtual bool ofbx::IElementProperty::getValues (\fBi64\fP * values, int max_size) const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::Property\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
