.TH "ofbx::ClusterImpl" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::ClusterImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBofbx::Cluster\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClusterImpl\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "const int * \fBgetIndices\fP () const override"
.br
.ti -1c
.RI "int \fBgetIndicesCount\fP () const override"
.br
.ti -1c
.RI "const double * \fBgetWeights\fP () const override"
.br
.ti -1c
.RI "int \fBgetWeightsCount\fP () const override"
.br
.ti -1c
.RI "\fBMatrix\fP \fBgetTransformMatrix\fP () const override"
.br
.ti -1c
.RI "\fBMatrix\fP \fBgetTransformLinkMatrix\fP () const override"
.br
.ti -1c
.RI "\fBObject\fP * \fBgetLink\fP () const override"
.br
.ti -1c
.RI "bool \fBpostprocess\fP ()"
.br
.ti -1c
.RI "\fBType\fP \fBgetType\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBObject\fP * \fBlink\fP = nullptr"
.br
.ti -1c
.RI "\fBSkin\fP * \fBskin\fP = nullptr"
.br
.ti -1c
.RI "std::vector< int > \fBindices\fP"
.br
.ti -1c
.RI "std::vector< double > \fBweights\fP"
.br
.ti -1c
.RI "\fBMatrix\fP \fBtransform_matrix\fP"
.br
.ti -1c
.RI "\fBMatrix\fP \fBtransform_link_matrix\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::ClusterImpl::ClusterImpl (const \fBScene\fP & _scene, const \fBIElement\fP & _element)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const int* ofbx::ClusterImpl::getIndices () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Cluster\fP\&.
.SS "int ofbx::ClusterImpl::getIndicesCount () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Cluster\fP\&.
.SS "\fBObject\fP* ofbx::ClusterImpl::getLink () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Cluster\fP\&.
.SS "\fBMatrix\fP ofbx::ClusterImpl::getTransformLinkMatrix () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Cluster\fP\&.
.SS "\fBMatrix\fP ofbx::ClusterImpl::getTransformMatrix () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Cluster\fP\&.
.SS "\fBType\fP ofbx::ClusterImpl::getType () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Object\fP\&.
.SS "const double* ofbx::ClusterImpl::getWeights () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Cluster\fP\&.
.SS "int ofbx::ClusterImpl::getWeightsCount () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Cluster\fP\&.
.SS "bool ofbx::ClusterImpl::postprocess ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<int> ofbx::ClusterImpl::indices"

.SS "\fBObject\fP* ofbx::ClusterImpl::link = nullptr"

.SS "\fBSkin\fP* ofbx::ClusterImpl::skin = nullptr"

.SS "\fBMatrix\fP ofbx::ClusterImpl::transform_link_matrix"

.SS "\fBMatrix\fP ofbx::ClusterImpl::transform_matrix"

.SS "std::vector<double> ofbx::ClusterImpl::weights"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
