.TH "ofbx::Mesh" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::Mesh \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ofbx\&.h>\fP
.PP
Inherits \fBofbx::Object\fP\&.
.PP
Inherited by \fBofbx::MeshImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMesh\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "virtual const \fBGeometry\fP * \fBgetGeometry\fP () const =0"
.br
.ti -1c
.RI "virtual \fBMatrix\fP \fBgetGeometricMatrix\fP () const =0"
.br
.ti -1c
.RI "virtual const \fBMaterial\fP * \fBgetMaterial\fP (int idx) const =0"
.br
.ti -1c
.RI "virtual int \fBgetMaterialCount\fP () const =0"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBType\fP \fBs_type\fP = \fBType::MESH\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::Mesh::Mesh (const \fBScene\fP & _scene, const \fBIElement\fP & _element)"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBMatrix\fP ofbx::Mesh::getGeometricMatrix () const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::MeshImpl\fP\&.
.SS "virtual const \fBGeometry\fP* ofbx::Mesh::getGeometry () const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::MeshImpl\fP\&.
.SS "virtual const \fBMaterial\fP* ofbx::Mesh::getMaterial (int idx) const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::MeshImpl\fP\&.
.SS "virtual int ofbx::Mesh::getMaterialCount () const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::MeshImpl\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBType\fP ofbx::Mesh::s_type = \fBType::MESH\fP\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
