.TH "ofbx::Scene::Connection" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::Scene::Connection \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBOBJECT_OBJECT\fP, \fBOBJECT_PROPERTY\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBType\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBu64\fP \fBfrom\fP"
.br
.ti -1c
.RI "\fBu64\fP \fBto\fP"
.br
.ti -1c
.RI "\fBDataView\fP \fBproperty\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBofbx::Scene::Connection::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOBJECT_OBJECT \fP\fP
.TP
\fB\fIOBJECT_PROPERTY \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "\fBu64\fP ofbx::Scene::Connection::from"

.SS "\fBDataView\fP ofbx::Scene::Connection::property"

.SS "\fBu64\fP ofbx::Scene::Connection::to"

.SS "\fBType\fP ofbx::Scene::Connection::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
