.TH "ofbx::GeometryImpl" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::GeometryImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBofbx::Geometry\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNewVertex\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBVertexDataMapping\fP { \fBBY_POLYGON_VERTEX\fP, \fBBY_POLYGON\fP, \fBBY_VERTEX\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeometryImpl\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "\fBType\fP \fBgetType\fP () const override"
.br
.ti -1c
.RI "int \fBgetVertexCount\fP () const override"
.br
.ti -1c
.RI "const \fBVec3\fP * \fBgetVertices\fP () const override"
.br
.ti -1c
.RI "const \fBVec3\fP * \fBgetNormals\fP () const override"
.br
.ti -1c
.RI "const \fBVec2\fP * \fBgetUVs\fP (int index=0) const override"
.br
.ti -1c
.RI "const \fBVec4\fP * \fBgetColors\fP () const override"
.br
.ti -1c
.RI "const \fBVec3\fP * \fBgetTangents\fP () const override"
.br
.ti -1c
.RI "const \fBSkin\fP * \fBgetSkin\fP () const override"
.br
.ti -1c
.RI "const int * \fBgetMaterials\fP () const override"
.br
.ti -1c
.RI "void \fBtriangulate\fP (const std::vector< int > &old_indices, std::vector< int > *indices, std::vector< int > *to_old)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBVec3\fP > \fBvertices\fP"
.br
.ti -1c
.RI "std::vector< \fBVec3\fP > \fBnormals\fP"
.br
.ti -1c
.RI "std::vector< \fBVec2\fP > \fBuvs\fP [\fBs_uvs_max\fP]"
.br
.ti -1c
.RI "std::vector< \fBVec4\fP > \fBcolors\fP"
.br
.ti -1c
.RI "std::vector< \fBVec3\fP > \fBtangents\fP"
.br
.ti -1c
.RI "std::vector< int > \fBmaterials\fP"
.br
.ti -1c
.RI "const \fBSkin\fP * \fBskin\fP = nullptr"
.br
.ti -1c
.RI "std::vector< int > \fBto_old_vertices\fP"
.br
.ti -1c
.RI "std::vector< \fBNewVertex\fP > \fBto_new_vertices\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBofbx::GeometryImpl::VertexDataMapping\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBY_POLYGON_VERTEX \fP\fP
.TP
\fB\fIBY_POLYGON \fP\fP
.TP
\fB\fIBY_VERTEX \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::GeometryImpl::GeometryImpl (const \fBScene\fP & _scene, const \fBIElement\fP & _element)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBVec4\fP* ofbx::GeometryImpl::getColors () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Geometry\fP\&.
.SS "const int* ofbx::GeometryImpl::getMaterials () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Geometry\fP\&.
.SS "const \fBVec3\fP* ofbx::GeometryImpl::getNormals () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Geometry\fP\&.
.SS "const \fBSkin\fP* ofbx::GeometryImpl::getSkin () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Geometry\fP\&.
.SS "const \fBVec3\fP* ofbx::GeometryImpl::getTangents () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Geometry\fP\&.
.SS "\fBType\fP ofbx::GeometryImpl::getType () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Object\fP\&.
.SS "const \fBVec2\fP* ofbx::GeometryImpl::getUVs (int index = \fC0\fP) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Geometry\fP\&.
.SS "int ofbx::GeometryImpl::getVertexCount () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Geometry\fP\&.
.SS "const \fBVec3\fP* ofbx::GeometryImpl::getVertices () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Geometry\fP\&.
.SS "void ofbx::GeometryImpl::triangulate (const std::vector< int > & old_indices, std::vector< int > * indices, std::vector< int > * to_old)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBVec4\fP> ofbx::GeometryImpl::colors"

.SS "std::vector<int> ofbx::GeometryImpl::materials"

.SS "std::vector<\fBVec3\fP> ofbx::GeometryImpl::normals"

.SS "const \fBSkin\fP* ofbx::GeometryImpl::skin = nullptr"

.SS "std::vector<\fBVec3\fP> ofbx::GeometryImpl::tangents"

.SS "std::vector<\fBNewVertex\fP> ofbx::GeometryImpl::to_new_vertices"

.SS "std::vector<int> ofbx::GeometryImpl::to_old_vertices"

.SS "std::vector<\fBVec2\fP> ofbx::GeometryImpl::uvs[\fBs_uvs_max\fP]"

.SS "std::vector<\fBVec3\fP> ofbx::GeometryImpl::vertices"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
