.TH "ofbx::AnimationCurveImpl" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::AnimationCurveImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBofbx::AnimationCurve\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimationCurveImpl\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "int \fBgetKeyCount\fP () const override"
.br
.ti -1c
.RI "const \fBi64\fP * \fBgetKeyTime\fP () const override"
.br
.ti -1c
.RI "const float * \fBgetKeyValue\fP () const override"
.br
.ti -1c
.RI "\fBType\fP \fBgetType\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBi64\fP > \fBtimes\fP"
.br
.ti -1c
.RI "std::vector< float > \fBvalues\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::AnimationCurveImpl::AnimationCurveImpl (const \fBScene\fP & _scene, const \fBIElement\fP & _element)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int ofbx::AnimationCurveImpl::getKeyCount () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::AnimationCurve\fP\&.
.SS "const \fBi64\fP* ofbx::AnimationCurveImpl::getKeyTime () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::AnimationCurve\fP\&.
.SS "const float* ofbx::AnimationCurveImpl::getKeyValue () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::AnimationCurve\fP\&.
.SS "\fBType\fP ofbx::AnimationCurveImpl::getType () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Object\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBi64\fP> ofbx::AnimationCurveImpl::times"

.SS "std::vector<float> ofbx::AnimationCurveImpl::values"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
