.TH "ofbx::Quat" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::Quat \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ofbx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.ti -1c
.RI "double \fBw\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double ofbx::Quat::w"

.SS "double ofbx::Quat::x"

.SS "double ofbx::Quat::y"

.SS "double ofbx::Quat::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
