.TH "ofbx::TakeInfo" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::TakeInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ofbx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDataView\fP \fBname\fP"
.br
.ti -1c
.RI "\fBDataView\fP \fBfilename\fP"
.br
.ti -1c
.RI "double \fBlocal_time_from\fP"
.br
.ti -1c
.RI "double \fBlocal_time_to\fP"
.br
.ti -1c
.RI "double \fBreference_time_from\fP"
.br
.ti -1c
.RI "double \fBreference_time_to\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBDataView\fP ofbx::TakeInfo::filename"

.SS "double ofbx::TakeInfo::local_time_from"

.SS "double ofbx::TakeInfo::local_time_to"

.SS "\fBDataView\fP ofbx::TakeInfo::name"

.SS "double ofbx::TakeInfo::reference_time_from"

.SS "double ofbx::TakeInfo::reference_time_to"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
