.TH "ofbx::NodeAttributeImpl" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::NodeAttributeImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBofbx::NodeAttribute\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeAttributeImpl\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "\fBType\fP \fBgetType\fP () const override"
.br
.ti -1c
.RI "\fBDataView\fP \fBgetAttributeType\fP () const override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDataView\fP \fBattribute_type\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::NodeAttributeImpl::NodeAttributeImpl (const \fBScene\fP & _scene, const \fBIElement\fP & _element)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBDataView\fP ofbx::NodeAttributeImpl::getAttributeType () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::NodeAttribute\fP\&.
.SS "\fBType\fP ofbx::NodeAttributeImpl::getType () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Object\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDataView\fP ofbx::NodeAttributeImpl::attribute_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
