.TH "ofbx::AnimationStackImpl" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::AnimationStackImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBofbx::AnimationStack\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimationStackImpl\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "const \fBAnimationLayer\fP * \fBgetLayer\fP (int index) const override"
.br
.ti -1c
.RI "\fBType\fP \fBgetType\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::AnimationStackImpl::AnimationStackImpl (const \fBScene\fP & _scene, const \fBIElement\fP & _element)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBAnimationLayer\fP* ofbx::AnimationStackImpl::getLayer (int index) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::AnimationStack\fP\&.
.SS "\fBType\fP ofbx::AnimationStackImpl::getType () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Object\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
