.TH "ofbx::AnimationCurveNodeImpl::Curve" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::AnimationCurveNodeImpl::Curve \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBAnimationCurve\fP * \fBcurve\fP = nullptr"
.br
.ti -1c
.RI "const \fBScene::Connection\fP * \fBconnection\fP = nullptr"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const \fBScene::Connection\fP* ofbx::AnimationCurveNodeImpl::Curve::connection = nullptr"

.SS "const \fBAnimationCurve\fP* ofbx::AnimationCurveNodeImpl::Curve::curve = nullptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
