.TH "ofbx::LimbNodeImpl" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::LimbNodeImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBofbx::Object\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLimbNodeImpl\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "\fBType\fP \fBgetType\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::LimbNodeImpl::LimbNodeImpl (const \fBScene\fP & _scene, const \fBIElement\fP & _element)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBType\fP ofbx::LimbNodeImpl::getType () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBofbx::Object\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
