.TH "ofbx::AnimationLayer" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::AnimationLayer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ofbx\&.h>\fP
.PP
Inherits \fBofbx::Object\fP\&.
.PP
Inherited by \fBofbx::AnimationLayerImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimationLayer\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "virtual const \fBAnimationCurveNode\fP * \fBgetCurveNode\fP (int index) const =0"
.br
.ti -1c
.RI "virtual const \fBAnimationCurveNode\fP * \fBgetCurveNode\fP (const \fBObject\fP &bone, const char *property) const =0"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBType\fP \fBs_type\fP = \fBType::ANIMATION_LAYER\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::AnimationLayer::AnimationLayer (const \fBScene\fP & _scene, const \fBIElement\fP & _element)"

.SH "Member Function Documentation"
.PP 
.SS "virtual const \fBAnimationCurveNode\fP* ofbx::AnimationLayer::getCurveNode (int index) const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::AnimationLayerImpl\fP\&.
.SS "virtual const \fBAnimationCurveNode\fP* ofbx::AnimationLayer::getCurveNode (const \fBObject\fP & bone, const char * property) const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::AnimationLayerImpl\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBType\fP ofbx::AnimationLayer::s_type = \fBType::ANIMATION_LAYER\fP\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
