.TH "ofbx::OptionalError< T >" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::OptionalError< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionalError\fP (\fBError\fP error)"
.br
.ti -1c
.RI "\fBOptionalError\fP (T _value)"
.br
.ti -1c
.RI "T \fBgetValue\fP () const "
.br
.ti -1c
.RI "bool \fBisError\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "T \fBvalue\fP"
.br
.ti -1c
.RI "bool \fBis_error\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBofbx::OptionalError\fP< T >::\fBOptionalError\fP (\fBError\fP error)\fC [inline]\fP"

.SS "template<typename T > \fBofbx::OptionalError\fP< T >::\fBOptionalError\fP (T _value)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > T \fBofbx::OptionalError\fP< T >::getValue () const\fC [inline]\fP"

.SS "template<typename T > bool \fBofbx::OptionalError\fP< T >::isError ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T > bool \fBofbx::OptionalError\fP< T >::is_error\fC [private]\fP"

.SS "template<typename T > T \fBofbx::OptionalError\fP< T >::value\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
