.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ofbx.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ofbx.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBofbx::Vec2\fP"
.br
.ti -1c
.RI "struct \fBofbx::Vec3\fP"
.br
.ti -1c
.RI "struct \fBofbx::Vec4\fP"
.br
.ti -1c
.RI "struct \fBofbx::Matrix\fP"
.br
.ti -1c
.RI "struct \fBofbx::Quat\fP"
.br
.ti -1c
.RI "struct \fBofbx::Color\fP"
.br
.ti -1c
.RI "struct \fBofbx::DataView\fP"
.br
.ti -1c
.RI "struct \fBofbx::IElementProperty\fP"
.br
.ti -1c
.RI "struct \fBofbx::IElement\fP"
.br
.ti -1c
.RI "struct \fBofbx::Object\fP"
.br
.ti -1c
.RI "struct \fBofbx::Texture\fP"
.br
.ti -1c
.RI "struct \fBofbx::Material\fP"
.br
.ti -1c
.RI "struct \fBofbx::Cluster\fP"
.br
.ti -1c
.RI "struct \fBofbx::Skin\fP"
.br
.ti -1c
.RI "struct \fBofbx::NodeAttribute\fP"
.br
.ti -1c
.RI "struct \fBofbx::Geometry\fP"
.br
.ti -1c
.RI "struct \fBofbx::Mesh\fP"
.br
.ti -1c
.RI "struct \fBofbx::AnimationStack\fP"
.br
.ti -1c
.RI "struct \fBofbx::AnimationLayer\fP"
.br
.ti -1c
.RI "struct \fBofbx::AnimationCurve\fP"
.br
.ti -1c
.RI "struct \fBofbx::AnimationCurveNode\fP"
.br
.ti -1c
.RI "struct \fBofbx::TakeInfo\fP"
.br
.ti -1c
.RI "struct \fBofbx::IScene\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBofbx\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBofbx::u8\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBofbx::u16\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBofbx::u32\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBofbx::u64\fP"
.br
.ti -1c
.RI "typedef long long \fBofbx::i64\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBofbx::RotationOrder\fP { \fBofbx::RotationOrder::EULER_XYZ\fP, \fBofbx::RotationOrder::EULER_XZY\fP, \fBofbx::RotationOrder::EULER_YZX\fP, \fBofbx::RotationOrder::EULER_YXZ\fP, \fBofbx::RotationOrder::EULER_ZXY\fP, \fBofbx::RotationOrder::EULER_ZYX\fP, \fBofbx::RotationOrder::SPHERIC_XYZ\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "IScene * \fBofbx::load\fP (const u8 *data, int size)"
.br
.ti -1c
.RI "const char * \fBofbx::getError\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
