.TH "ofbx::Skin" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::Skin \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ofbx\&.h>\fP
.PP
Inherits \fBofbx::Object\fP\&.
.PP
Inherited by \fBofbx::SkinImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSkin\fP (const \fBScene\fP &_scene, const \fBIElement\fP &_element)"
.br
.ti -1c
.RI "virtual int \fBgetClusterCount\fP () const =0"
.br
.ti -1c
.RI "virtual const \fBCluster\fP * \fBgetCluster\fP (int idx) const =0"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBType\fP \fBs_type\fP = \fBType::SKIN\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::Skin::Skin (const \fBScene\fP & _scene, const \fBIElement\fP & _element)"

.SH "Member Function Documentation"
.PP 
.SS "virtual const \fBCluster\fP* ofbx::Skin::getCluster (int idx) const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::SkinImpl\fP\&.
.SS "virtual int ofbx::Skin::getClusterCount () const\fC [pure virtual]\fP"

.PP
Implemented in \fBofbx::SkinImpl\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBType\fP ofbx::Skin::s_type = \fBType::SKIN\fP\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
