.TH "ofbx::GeometryImpl::NewVertex" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ofbx::GeometryImpl::NewVertex \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~NewVertex\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP = -1"
.br
.ti -1c
.RI "\fBNewVertex\fP * \fBnext\fP = nullptr"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ofbx::GeometryImpl::NewVertex::~NewVertex ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int ofbx::GeometryImpl::NewVertex::index = -1"

.SS "\fBNewVertex\fP* ofbx::GeometryImpl::NewVertex::next = nullptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
