.TH "Particle" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Particle \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBParticle\fP &that) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBpos\fP"
.br
.ti -1c
.RI "glm::vec3 \fBspeed\fP"
.br
.ti -1c
.RI "unsigned char \fBr\fP"
.br
.ti -1c
.RI "unsigned char \fBg\fP"
.br
.ti -1c
.RI "unsigned char \fBb\fP"
.br
.ti -1c
.RI "unsigned char \fBa\fP"
.br
.ti -1c
.RI "float \fBsize\fP"
.br
.ti -1c
.RI "float \fBangle\fP"
.br
.ti -1c
.RI "float \fBweight\fP"
.br
.ti -1c
.RI "float \fBlife\fP"
.br
.ti -1c
.RI "float \fBcameradistance\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool Particle::operator< (const \fBParticle\fP & that) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned char Particle::a"

.SS "float Particle::angle"

.SS "unsigned char Particle::b"

.SS "float Particle::cameradistance"

.SS "unsigned char Particle::g"

.SS "float Particle::life"

.SS "glm::vec3 Particle::pos"

.SS "unsigned char Particle::r"

.SS "float Particle::size"

.SS "glm::vec3 Particle::speed"

.SS "float Particle::weight"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
