.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/primitive_object.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/primitive_object.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'primitive_object\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_primitive_list\fP ()"
.br
.RI "\fIput all primitive defined object into g_primitive_list \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const float \fBhalf_side_len\fP = 0\&.5f"
.br
.ti -1c
.RI "\fBmp_primitive\fP \fBg_primitive_list\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void init_primitive_list ()"

.PP
put all primitive defined object into g_primitive_list 
.SH "Variable Documentation"
.PP 
.SS "\fBmp_primitive\fP g_primitive_list"
the primitive object of g_primitive_list will be referenced by some ui components 
.SS "const float half_side_len = 0\&.5f"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
