.TH "primitive_object" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
primitive_object \- \fBprimitive_object\fP represent basic data struct which will be inputed into
.br
a vertex shader  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <primitive_object\&.h>\fP
.PP
Inherited by \fBprimitive_cube\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprimitive_object\fP ()"
.br
.ti -1c
.RI "virtual \fB~primitive_object\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLuint \fB_vao\fP"
.br
.ti -1c
.RI "GLuint \fB_vbo\fP"
.br
.ti -1c
.RI "GLuint \fB_ebo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBprimitive_object\fP represent basic data struct which will be inputed into
.br
a vertex shader 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "primitive_object::primitive_object ()\fC [inline]\fP"

.SS "virtual primitive_object::~primitive_object ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "GLuint primitive_object::_ebo"

.SS "GLuint primitive_object::_vao"

.SS "GLuint primitive_object::_vbo"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
