.TH "primitive_cube" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
primitive_cube \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <primitive_object\&.h>\fP
.PP
Inherits \fBprimitive_object\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprimitive_cube\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static GLfloat \fB_vertices\fP []"
.br
.ti -1c
.RI "static GLushort \fB_indices\fP []"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "primitive_cube::primitive_cube ()"

.SH "Member Data Documentation"
.PP 
.SS "GLushort primitive_cube::_indices\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    0, 4, 5,
    5, 1, 0,

    3, 2, 6,
    6, 7, 3,

    7, 4, 0,
    0, 3, 7,

    6, 2, 1,
    1, 5, 6,

    0, 1, 2,
    2, 3, 0,

    4, 7, 6,
    6, 5, 4
}
.fi
.SS "GLfloat primitive_cube::_vertices\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    -half_side_len, -half_side_len, -half_side_len, 1\&.0f, 1\&.0f, 1\&.0f, 0\&.0f, 0\&.0f,
    half_side_len, -half_side_len, -half_side_len, 1\&.0f, 1\&.0f, 0\&.0f, 1\&.0f, 0\&.0f,
    half_side_len, -half_side_len, half_side_len, 1\&.0f, 0\&.0f, 1\&.0f, 1\&.0f, 1\&.0f,
    -half_side_len, -half_side_len, half_side_len, 0\&.0f, 1\&.0f, 1\&.0f, 0\&.0f, 1\&.0f,
    -half_side_len, half_side_len, -half_side_len, 0\&.0f, 0\&.0f, 1\&.0f, 0\&.0f, 1\&.0f,
    half_side_len, half_side_len, -half_side_len, 1\&.0f, 0\&.0f, 0\&.0f, 1\&.0f, 1\&.0f,
    half_side_len, half_side_len, half_side_len, 0\&.0f, 1\&.0f, 0\&.0f, 0\&.0f, 1\&.0f,
    -half_side_len, half_side_len, half_side_len, 0\&.0f, 0\&.0f, 0\&.0f, 1\&.0f, 1\&.0f,
    }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
