.TH "project_edit" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
project_edit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <project_edit\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBproject_edit\fP (\fBbase_ui_component\fP &fb)"
.br
.ti -1c
.RI "void \fBobjects_view\fP ()"
.br
.ti -1c
.RI "void \fBpopup_context_menu\fP ()"
.br
.ti -1c
.RI "void \fBclear_sel_item\fP ()"
.br
.ti -1c
.RI "\fBbase_ui_component\fP * \fBcurrent_object\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBview_object\fP (\fBbase_ui_component\fP &fb)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBbase_ui_component\fP & \fB_root\fP"
.br
.ti -1c
.RI "\fBbase_ui_component\fP * \fB_pcurrent_object\fP"
.br
.ti -1c
.RI "\fBbase_ui_component\fP * \fB_pcopy_object\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "project_edit::project_edit (\fBbase_ui_component\fP & fb)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void project_edit::clear_sel_item ()\fC [inline]\fP"

.SS "\fBbase_ui_component\fP* project_edit::current_object ()\fC [inline]\fP"

.SS "void project_edit::objects_view ()"

.SS "void project_edit::popup_context_menu ()"

.SS "void project_edit::view_object (\fBbase_ui_component\fP & fb)\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBbase_ui_component\fP* project_edit::_pcopy_object\fC [private]\fP"

.SS "\fBbase_ui_component\fP* project_edit::_pcurrent_object\fC [private]\fP"

.SS "\fBbase_ui_component\fP& project_edit::_root\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
