.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/project_edit.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/project_edit.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'project_edit\&.h'\fP
.br
\fC#include 'user_control_imgui\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
