.TH "property_range" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
property_range \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <control_common_def\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBproperty_range\fP (void *phead, int len)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fB_p_head_address\fP"
.br
.ti -1c
.RI "int \fB_len\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "property_range::property_range (void * phead, int len)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int property_range::_len"

.SS "void* property_range::_p_head_address"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
