.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/renderTransform.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/renderTransform.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <glm/glm\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomRenderTranslation\fP"
.br
.ti -1c
.RI "struct \fBCustomRenderTranslation::RenderTransformation\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
