.TH "res_texture_list" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
res_texture_list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <res_output\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBres_texture_list\fP ()"
.br
.ti -1c
.RI "\fB~res_texture_list\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtexture_width\fP"
.br
.ti -1c
.RI "int \fBtexture_height\fP"
.br
.ti -1c
.RI "unsigned int \fBtexture_id\fP"
.br
.ti -1c
.RI "string \fBtexture_pack_file\fP"
.br
.ti -1c
.RI "string \fBtexture_data_file\fP"
.br
.ti -1c
.RI "\fBvres_txt_cd\fP \fBvtexture_coordinates\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "res_texture_list::res_texture_list ()\fC [inline]\fP"

.SS "res_texture_list::~res_texture_list ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "string res_texture_list::texture_data_file"

.SS "int res_texture_list::texture_height"

.SS "unsigned int res_texture_list::texture_id"

.SS "string res_texture_list::texture_pack_file"

.SS "int res_texture_list::texture_width"

.SS "\fBvres_txt_cd\fP res_texture_list::vtexture_coordinates"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
