.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/res_output.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/res_output.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBres_texture_coordinate\fP"
.br
.ti -1c
.RI "struct \fBres_texture_list\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef vector< \fBres_texture_coordinate\fP > \fBvres_txt_cd\fP"
.br
.ti -1c
.RI "typedef vector< \fBres_texture_list\fP > \fBvres_txt_list\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBvres_txt_list\fP \fBg_vres_texture_list\fP"
.br
.ti -1c
.RI "int \fBg_cur_texture_id_index\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef vector<\fBres_texture_coordinate\fP> \fBvres_txt_cd\fP"

.SS "typedef vector<\fBres_texture_list\fP> \fBvres_txt_list\fP"

.SH "Variable Documentation"
.PP 
.SS "int g_cur_texture_id_index"

.SS "\fBvres_txt_list\fP g_vres_texture_list"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
