.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/res_output.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/res_output.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'res_output\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBvres_txt_list\fP \fBg_vres_texture_list\fP"
.br
.ti -1c
.RI "int \fBg_cur_texture_id_index\fP =0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int g_cur_texture_id_index =0"

.SS "\fBvres_txt_list\fP g_vres_texture_list"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
