.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/res_edit.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/res_edit.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'res_edit\&.h'\fP
.br
\fC#include 'res_output\&.h'\fP
.br
\fC#include 'user_control_imgui\&.h'\fP
.br
\fC#include <windows\&.h>\fP
.br
\fC#include <locale\&.h>\fP
.br
\fC#include <ShlObj\&.h>\fP
.br
\fC#include <Commdlg\&.h>\fP
.br
\fC#include 'texture_res_load\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
