.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/res_edit.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/res_edit.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBres_edit\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFILE_NAME_LEN\fP   50"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FILE_NAME_LEN   50"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
