.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/res_internal.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/res_internal.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'res_internal\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBg_txt_width_intl\fP"
.br
.ti -1c
.RI "int \fBg_txt_height_intl\fP"
.br
.ti -1c
.RI "int \fBg_txt_id_intl\fP"
.br
.ti -1c
.RI "\fBmtxt_internal\fP \fBg_mtxt_intl\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBmtxt_internal\fP g_mtxt_intl"

.SS "int g_txt_height_intl"

.SS "int g_txt_id_intl"

.SS "int g_txt_width_intl"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
