.TH "res_texture_coordinate" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
res_texture_coordinate \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <res_output\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBres_texture_coordinate\fP ()"
.br
.ti -1c
.RI "float \fBowidth\fP ()"
.br
.ti -1c
.RI "float \fBoheight\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fB_file_name\fP"
.br
.ti -1c
.RI "float \fB_x0\fP"
.br
.ti -1c
.RI "float \fB_y0\fP"
.br
.ti -1c
.RI "float \fB_x1\fP"
.br
.ti -1c
.RI "float \fB_y1\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "res_texture_coordinate::res_texture_coordinate ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "float res_texture_coordinate::oheight ()\fC [inline]\fP"

.SS "float res_texture_coordinate::owidth ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "string res_texture_coordinate::_file_name"

.SS "float res_texture_coordinate::_x0"

.SS "float res_texture_coordinate::_x1"

.SS "float res_texture_coordinate::_y0"

.SS "float res_texture_coordinate::_y1"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
