.TH "shader_uf" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shader_uf \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shader_uf\&.h>\fP
.PP
Inherited by \fBshader_uf_double\fP, \fBshader_uf_float\fP, \fBshader_uf_int\fP, and \fBshader_uf_uint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBedit\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBoutput_2_json\fP (Value &jvalue)"
.br
.ti -1c
.RI "virtual void \fBinit_from_json\fP (Value &jvalue)"
.br
.ti -1c
.RI "virtual void * \fBget_data_head\fP ()=0"
.br
.ti -1c
.RI "\fBshader_uf\fP (GLuint \fBusize\fP, GLuint el_sz)"
.br
.ti -1c
.RI "void \fBset_type\fP (GLenum uft)"
.br
.ti -1c
.RI "GLenum \fBget_type\fP ()"
.br
.ti -1c
.RI "virtual \fB~shader_uf\fP ()"
.br
.ti -1c
.RI "GLuint \fBusize\fP ()"
.br
.ti -1c
.RI "GLuint \fBelsize\fP ()"
.br
.ti -1c
.RI "virtual void \fBset_to_loaction\fP (GLuint location)=0"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fB_unf_name\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "GLuint \fB_el_size\fP"
.br
.ti -1c
.RI "GLuint \fB_usize\fP"
.br
.ti -1c
.RI "GLenum \fB_utype\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "shader_uf::shader_uf (GLuint usize, GLuint el_sz)\fC [inline]\fP"

.SS "virtual shader_uf::~shader_uf ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void shader_uf::edit ()\fC [pure virtual]\fP"

.PP
Implemented in \fBshader_uf_double\fP, \fBshader_uf_uint\fP, \fBshader_uf_int\fP, and \fBshader_uf_float\fP\&.
.SS "GLuint shader_uf::elsize ()\fC [inline]\fP"

.SS "virtual void* shader_uf::get_data_head ()\fC [pure virtual]\fP"

.PP
Implemented in \fBshader_uf_double\fP, \fBshader_uf_uint\fP, \fBshader_uf_int\fP, and \fBshader_uf_float\fP\&.
.SS "GLenum shader_uf::get_type ()\fC [inline]\fP"

.SS "void shader_uf::init_from_json (Value & jvalue)\fC [virtual]\fP"

.PP
Reimplemented in \fBshader_uf_double\fP, \fBshader_uf_uint\fP, \fBshader_uf_int\fP, and \fBshader_uf_float\fP\&.
.SS "void shader_uf::output_2_json (Value & jvalue)\fC [virtual]\fP"

.PP
Reimplemented in \fBshader_uf_double\fP, \fBshader_uf_uint\fP, \fBshader_uf_int\fP, and \fBshader_uf_float\fP\&.
.SS "virtual void shader_uf::set_to_loaction (GLuint location)\fC [pure virtual]\fP"

.PP
Implemented in \fBshader_uf_double\fP, \fBshader_uf_uint\fP, \fBshader_uf_int\fP, and \fBshader_uf_float\fP\&.
.SS "void shader_uf::set_type (GLenum uft)\fC [inline]\fP"

.SS "GLuint shader_uf::usize ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "GLuint shader_uf::_el_size\fC [protected]\fP"

.SS "string shader_uf::_unf_name"

.SS "GLuint shader_uf::_usize\fC [protected]\fP"

.SS "GLenum shader_uf::_utype\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
