.TH "shader_uf_assist< T >" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shader_uf_assist< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shader_uf\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshader_uf_assist\fP (string key)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static T * \fBcreate_new_obj\fP (GLuint usize, GLuint el_sz)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBshader_uf_assist\fP< T >::\fBshader_uf_assist\fP (string key)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static T* \fBshader_uf_assist\fP< T >::create_new_obj (GLuint usize, GLuint el_sz)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
