.TH "shader_uf_int" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shader_uf_int \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shader_uf\&.h>\fP
.PP
Inherits \fBshader_uf\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshader_uf_int\fP (GLuint \fBusize\fP, GLuint el_sz)"
.br
.ti -1c
.RI "void * \fBget_data_head\fP ()"
.br
.ti -1c
.RI "void \fBset_to_loaction\fP (GLuint location)"
.br
.ti -1c
.RI "void \fBset_ivalue\fP (int *pivalue, GLuint len)"
.br
.ti -1c
.RI "void \fBedit\fP ()"
.br
.ti -1c
.RI "void \fBoutput_2_json\fP (Value &jvalue)"
.br
.ti -1c
.RI "void \fBinit_from_json\fP (Value &jvalue)"
.br
.ti -1c
.RI "\fB~shader_uf_int\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int * \fB_pivalue\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "shader_uf_int::shader_uf_int (GLuint usize, GLuint el_sz)\fC [inline]\fP"

.SS "shader_uf_int::~shader_uf_int ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void shader_uf_int::edit ()\fC [virtual]\fP"

.PP
Implements \fBshader_uf\fP\&.
.SS "void* shader_uf_int::get_data_head ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBshader_uf\fP\&.
.SS "void shader_uf_int::init_from_json (Value & jvalue)\fC [virtual]\fP"

.PP
Reimplemented from \fBshader_uf\fP\&.
.SS "void shader_uf_int::output_2_json (Value & jvalue)\fC [virtual]\fP"

.PP
Reimplemented from \fBshader_uf\fP\&.
.SS "void shader_uf_int::set_ivalue (int * pivalue, GLuint len)\fC [inline]\fP"

.SS "void shader_uf_int::set_to_loaction (GLuint location)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBshader_uf\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int* shader_uf_int::_pivalue\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
