.TH "shader_attribute" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shader_attribute \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic3d\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshader_attribute\fP ()"
.br
.ti -1c
.RI "\fBshader_attribute\fP (\fBen_attribute_type\fP type, GLuint location)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBen_attribute_type\fP \fB_type\fP"
.br
.ti -1c
.RI "GLuint \fB_location\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "shader_attribute::shader_attribute ()\fC [inline]\fP"

.SS "shader_attribute::shader_attribute (\fBen_attribute_type\fP type, GLuint location)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "GLuint shader_attribute::_location"

.SS "\fBen_attribute_type\fP shader_attribute::_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
