.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/shader_uf.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/shader_uf.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'shader_uf\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'user_control_imgui\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "Factory< \fBshader_uf\fP > & \fBget_shader_uf_fc\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Factory<\fBshader_uf\fP>& get_shader_uf_fc ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
