.TH "shader_uniform" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shader_uniform \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic3d\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshader_uniform\fP ()"
.br
.ti -1c
.RI "\fBshader_uniform\fP (\fBen_uniform_type\fP type, GLuint location)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBen_uniform_type\fP \fB_type\fP"
.br
.ti -1c
.RI "GLuint \fB_location\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "shader_uniform::shader_uniform ()\fC [inline]\fP"

.SS "shader_uniform::shader_uniform (\fBen_uniform_type\fP type, GLuint location)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "GLuint shader_uniform::_location"

.SS "\fBen_uniform_type\fP shader_uniform::_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
