.TH "shader_assist< T >" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shader_assist< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic3d\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshader_assist\fP (string key)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBshader_assist\fP< T >::\fBshader_assist\fP (string key)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
