.TH "shader_variable" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shader_variable \- basic variable type of the shader 
.br
 

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <af_shader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshader_variable\fP ()"
.br
.ti -1c
.RI "\fBshader_variable\fP (GLenum vtp, GLuint loc, GLuint size)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLenum \fB_variable_type\fP"
.br
.ti -1c
.RI "GLuint \fB_location\fP"
.br
.ti -1c
.RI "GLuint \fB_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
basic variable type of the shader 
.br

.SH "Constructor & Destructor Documentation"
.PP 
.SS "shader_variable::shader_variable ()\fC [inline]\fP"

.SS "shader_variable::shader_variable (GLenum vtp, GLuint loc, GLuint size)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "GLuint shader_variable::_location"

.SS "GLuint shader_variable::_size"

.SS "GLenum shader_variable::_variable_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
