.TH "tdefl_output_buffer" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tdefl_output_buffer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBm_size\fP"
.br
.ti -1c
.RI "size_t \fBm_capacity\fP"
.br
.ti -1c
.RI "\fBmz_uint8\fP * \fBm_pBuf\fP"
.br
.ti -1c
.RI "\fBmz_bool\fP \fBm_expandable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "size_t tdefl_output_buffer::m_capacity"

.SS "\fBmz_bool\fP tdefl_output_buffer::m_expandable"

.SS "\fBmz_uint8\fP* tdefl_output_buffer::m_pBuf"

.SS "size_t tdefl_output_buffer::m_size"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
