.TH "tdefl_sym_freq" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tdefl_sym_freq \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmz_uint16\fP \fBm_key\fP"
.br
.ti -1c
.RI "\fBmz_uint16\fP \fBm_sym_index\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmz_uint16\fP tdefl_sym_freq::m_key"

.SS "\fBmz_uint16\fP tdefl_sym_freq::m_sym_index"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
