.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/texture_res_load.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/texture_res_load.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'res_output\&.h'\fP
.br
\fC#include 'json/json\&.h'\fP
.br
\fC#include 'res_internal\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtexture_res_load\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBload_texture_info\fP (\fBres_texture_list\fP &rtlist, string &str_txt_pack_file, string &str_txt_data_file)"
.br
.ti -1c
.RI "void \fBload_internal_texture_res\fP (\fBmtxt_internal\fP &mptxt, unsigned int txtresid, unsigned int txtformatid)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void load_internal_texture_res (\fBmtxt_internal\fP & mptxt, unsigned int txtresid, unsigned int txtformatid)"

.SS "bool load_texture_info (\fBres_texture_list\fP & rtlist, string & str_txt_pack_file, string & str_txt_data_file)"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
