.TH "texture_shader" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
texture_shader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <texture_shader\&.h>\fP
.PP
Inherits \fBbasic_shader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtexture_shader\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "texture_shader::texture_shader ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
