.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/texture_shader.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/texture_shader.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'basic3d\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtexture_shader\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBREG_SHADER\fP (\fBtexture_shader\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "REG_SHADER (\fBtexture_shader\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
