.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/texture_res_load.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/texture_res_load.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'texture_res_load\&.h'\fP
.br
\fC#include <GL/gl3w\&.h>\fP
.br
\fC#include <GLFW/glfw3\&.h>\fP
.br
\fC#include 'SOIL\&.h'\fP
.br
\fC#include 'texture\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBload_texture_info\fP (\fBres_texture_list\fP &rtlist, string &str_txt_pack_file, string &str_txt_data_file)"
.br
.ti -1c
.RI "void \fBload_internal_texture_res\fP (\fBmtxt_internal\fP &mptxt, unsigned int txtresid, unsigned int txtformatid)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBg_cureent_project_file_path\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void load_internal_texture_res (\fBmtxt_internal\fP & mptxt, unsigned int txtresid, unsigned int txtformatid)"

.SS "bool load_texture_info (\fBres_texture_list\fP & rtlist, string & str_txt_pack_file, string & str_txt_data_file)"

.SH "Variable Documentation"
.PP 
.SS "string g_cureent_project_file_path"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
