.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/texture_shader.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/texture_shader.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'texture_shader\&.h'\fP
.br
\fC#include 'control_common_def\&.h'\fP
.br
\fC#include <glm\&.hpp>\fP
.br
\fC#include <gtc/matrix_transform\&.hpp>\fP
.br
\fC#include <gtc/type_ptr\&.hpp>\fP
.br
\fC#include 'SOIL\&.h'\fP
.br
\fC#include 'texture\&.h'\fP
.br
\fC#include 'camera\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCHECK_SHADER_STATUS\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const GLchar * \fBts_vertexSource\fP"
.br
.ti -1c
.RI "static const GLchar * \fBts_fragmentSource\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CHECK_SHADER_STATUS"

.SH "Variable Documentation"
.PP 
.SS "const GLchar* ts_fragmentSource\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= R"glsl(
    varying vec2 Textcoord;
    uniform sampler2D text;
    void main()
    {
        gl_FragColor = texture(text, Textcoord);
    }
)glsl"
.fi
.SS "const GLchar* ts_vertexSource\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= R"glsl(
    attribute vec3 position;
    attribute vec2 textcoord;
    attribute vec3 normal;

    varying vec2 Textcoord;
    uniform mat4 proj;
    uniform mat4 view;
    uniform mat4 model;
    void main()
    {
         gl_Position = proj * view * model * vec4(position, 1\&.0);
        Textcoord = textcoord;
    }
)glsl"
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
