.TH "texture_res_load" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
texture_res_load \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <texture_res_load\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtexture_res_load\fP (\fBvres_txt_list\fP &texture_res_tar)"
.br
.ti -1c
.RI "void \fBload_res_from_json\fP (Value &jroot)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBvres_txt_list\fP & \fB_texture_res_tar\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "texture_res_load::texture_res_load (\fBvres_txt_list\fP & texture_res_tar)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void texture_res_load::load_res_from_json (Value & jroot)"

.SH "Member Data Documentation"
.PP 
.SS "\fBvres_txt_list\fP& texture_res_load::_texture_res_tar\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
