.TH "texture_unit" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
texture_unit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <res_internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtexture_unit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fB_x0\fP"
.br
.ti -1c
.RI "float \fB_y0\fP"
.br
.ti -1c
.RI "float \fB_x1\fP"
.br
.ti -1c
.RI "float \fB_y1\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "texture_unit::texture_unit ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float texture_unit::_x0"

.SS "float texture_unit::_x1"

.SS "float texture_unit::_y0"

.SS "float texture_unit::_y1"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
