.TH "tinfl_decompressor_tag" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinfl_decompressor_tag \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <miniz\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmz_uint32\fP \fBm_state\fP"
.br
.ti -1c
.RI "\fBmz_uint32\fP \fBm_num_bits\fP"
.br
.ti -1c
.RI "\fBmz_uint32\fP \fBm_zhdr0\fP"
.br
.ti -1c
.RI "\fBmz_uint32\fP \fBm_zhdr1\fP"
.br
.ti -1c
.RI "\fBmz_uint32\fP \fBm_z_adler32\fP"
.br
.ti -1c
.RI "\fBmz_uint32\fP \fBm_final\fP"
.br
.ti -1c
.RI "\fBmz_uint32\fP \fBm_type\fP"
.br
.ti -1c
.RI "\fBmz_uint32\fP \fBm_check_adler32\fP"
.br
.ti -1c
.RI "\fBmz_uint32\fP \fBm_dist\fP"
.br
.ti -1c
.RI "\fBmz_uint32\fP \fBm_counter\fP"
.br
.ti -1c
.RI "\fBmz_uint32\fP \fBm_num_extra\fP"
.br
.ti -1c
.RI "\fBmz_uint32\fP \fBm_table_sizes\fP [\fBTINFL_MAX_HUFF_TABLES\fP]"
.br
.ti -1c
.RI "\fBtinfl_bit_buf_t\fP \fBm_bit_buf\fP"
.br
.ti -1c
.RI "size_t \fBm_dist_from_out_buf_start\fP"
.br
.ti -1c
.RI "\fBtinfl_huff_table\fP \fBm_tables\fP [\fBTINFL_MAX_HUFF_TABLES\fP]"
.br
.ti -1c
.RI "\fBmz_uint8\fP \fBm_raw_header\fP [4]"
.br
.ti -1c
.RI "\fBmz_uint8\fP \fBm_len_codes\fP [\fBTINFL_MAX_HUFF_SYMBOLS_0\fP+\fBTINFL_MAX_HUFF_SYMBOLS_1\fP+137]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBtinfl_bit_buf_t\fP tinfl_decompressor_tag::m_bit_buf"

.SS "\fBmz_uint32\fP tinfl_decompressor_tag::m_check_adler32"

.SS "\fBmz_uint32\fP tinfl_decompressor_tag::m_counter"

.SS "\fBmz_uint32\fP tinfl_decompressor_tag::m_dist"

.SS "size_t tinfl_decompressor_tag::m_dist_from_out_buf_start"

.SS "\fBmz_uint32\fP tinfl_decompressor_tag::m_final"

.SS "\fBmz_uint8\fP tinfl_decompressor_tag::m_len_codes[\fBTINFL_MAX_HUFF_SYMBOLS_0\fP+\fBTINFL_MAX_HUFF_SYMBOLS_1\fP+137]"

.SS "\fBmz_uint32\fP tinfl_decompressor_tag::m_num_bits"

.SS "\fBmz_uint32\fP tinfl_decompressor_tag::m_num_extra"

.SS "\fBmz_uint8\fP tinfl_decompressor_tag::m_raw_header[4]"

.SS "\fBmz_uint32\fP tinfl_decompressor_tag::m_state"

.SS "\fBmz_uint32\fP tinfl_decompressor_tag::m_table_sizes[\fBTINFL_MAX_HUFF_TABLES\fP]"

.SS "\fBtinfl_huff_table\fP tinfl_decompressor_tag::m_tables[\fBTINFL_MAX_HUFF_TABLES\fP]"

.SS "\fBmz_uint32\fP tinfl_decompressor_tag::m_type"

.SS "\fBmz_uint32\fP tinfl_decompressor_tag::m_z_adler32"

.SS "\fBmz_uint32\fP tinfl_decompressor_tag::m_zhdr0"

.SS "\fBmz_uint32\fP tinfl_decompressor_tag::m_zhdr1"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
