.TH "tinfl_huff_table" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinfl_huff_table \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <miniz\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmz_uint8\fP \fBm_code_size\fP [\fBTINFL_MAX_HUFF_SYMBOLS_0\fP]"
.br
.ti -1c
.RI "\fBmz_int16\fP \fBm_look_up\fP [\fBTINFL_FAST_LOOKUP_SIZE\fP]"
.br
.ti -1c
.RI "\fBmz_int16\fP \fBm_tree\fP [\fBTINFL_MAX_HUFF_SYMBOLS_0\fP *2]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmz_uint8\fP tinfl_huff_table::m_code_size[\fBTINFL_MAX_HUFF_SYMBOLS_0\fP]"

.SS "\fBmz_int16\fP tinfl_huff_table::m_look_up[\fBTINFL_FAST_LOOKUP_SIZE\fP]"

.SS "\fBmz_int16\fP tinfl_huff_table::m_tree[\fBTINFL_MAX_HUFF_SYMBOLS_0\fP *2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
