.TH "ui_assembler" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui_assembler \- \fBui_assembler\fP is responsible for transferring project file to ui components or transferring ui components to project file
.br
 

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_assembler\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBui_assembler\fP (\fBbase_ui_component\fP &root)"
.br
.ti -1c
.RI "\fB~ui_assembler\fP ()"
.br
.ti -1c
.RI "bool \fBload_ui_component_from_file\fP (const char *file_path)"
.br
.RI "\fItransferring project file to ui components \fP"
.ti -1c
.RI "bool \fBoutput_ui_component_to_file\fP (const char *file_path)"
.br
.RI "\fItransferring ui components to ui project file \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBbase_ui_component\fP & \fB_root\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBui_assembler\fP is responsible for transferring project file to ui components or transferring ui components to project file
.br

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ui_assembler::ui_assembler (\fBbase_ui_component\fP & root)\fC [inline]\fP"

.SS "ui_assembler::~ui_assembler ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ui_assembler::load_ui_component_from_file (const char * file_path)"

.PP
transferring project file to ui components 
.PP
\fBParameters:\fP
.RS 4
\fIfile_path\fP project file path 
.RE
.PP
\fBReturns:\fP
.RS 4
true if success,false if failure 
.RE
.PP

.SS "bool ui_assembler::output_ui_component_to_file (const char * file_path)"

.PP
transferring ui components to ui project file 
.PP
\fBParameters:\fP
.RS 4
\fIfile_path\fP project file path 
.RE
.PP
\fBReturns:\fP
.RS 4
true if success,false if failure 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBbase_ui_component\fP& ui_assembler::_root\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
