.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ui_assembler.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ui_assembler.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'control_common_def\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBui_assembler\fP"
.br
.RI "\fI\fBui_assembler\fP is responsible for transferring project file to ui components or transferring ui components to project file
.br
\fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
