.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ui_assembler.cpp" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/ui_assembler.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ui_assembler\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'texture_res_load\&.h'\fP
.br
\fC#include 'af_shader\&.h'\fP
.br
\fC#include 'material\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
