.TH "G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/user_control_imgui.h" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/GitHub/my_imgui/my_imgui/examples/auto_future_graphics_design/user_control_imgui.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'imgui\&.h'\fP
.br
\fC#include 'imgui_internal\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIMGUI_DEFINE_MATH_OPERATORS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBIconTreeNode\fP (string &icon_name, const char *label, ImGuiTreeNodeFlags flags)"
.br
.ti -1c
.RI "bool \fBIconTreeNodeBehavior\fP (ImGuiID id, ImGuiTreeNodeFlags flags, string &icon_name, const char *label, const char *label_end)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IMGUI_DEFINE_MATH_OPERATORS"

.SH "Function Documentation"
.PP 
.SS "bool IconTreeNode (string & icon_name, const char * label, ImGuiTreeNodeFlags flags)"

.SS "bool IconTreeNodeBehavior (ImGuiID id, ImGuiTreeNodeFlags flags, string & icon_name, const char * label, const char * label_end)"

.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
