.TH "Vertex" 3 "Thu Jun 14 2018" "afd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vertex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mesh\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBposition\fP"
.br
.ti -1c
.RI "glm::vec2 \fBtexCoords\fP"
.br
.ti -1c
.RI "glm::vec3 \fBnormal\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 Vertex::normal"

.SS "glm::vec3 Vertex::position"

.SS "glm::vec2 Vertex::texCoords"


.SH "Author"
.PP 
Generated automatically by Doxygen for afd from the source code\&.
